---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: Busque información sobre problemas conocidos al usar Trident con Docker. 
---
= Problemas y limitaciones conocidos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Busque información sobre problemas conocidos y limitaciones cuando use Trident con Docker.



[[upgrading-trident-docker-volume-plugin-to-20-10-and-later-from-older-versions-results-in-upgrade-failure-with-the-no-such-file-or-directory-error]]
== Si se actualiza el complemento Trident Docker Volume Plugin a 20.10 y versiones posteriores, se produce un error de actualización sin dicho archivo o directorio.

.Solución alternativa
. Desactivar el plugin.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. Quitar el plugin.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. Vuelva a instalar el plugin proporcionando el extra `config` parámetro.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




[[volume-names-must-be-a-minimum-of-2-characters-in-length]]
== Los nombres de volumen deben tener una longitud mínima de 2 caracteres.


NOTE: Esta es una limitación de cliente de Docker. El cliente interpretará un nombre de carácter único como una ruta de Windows. https://github.com/moby/moby/issues/25773["Consulte el error 25773"^].



[[docker-swarm-has-certain-behaviors-that-prevent-trident-from-supporting-it-with-every-storage-and-driver-combination]]
== Docker Swarm tiene ciertos comportamientos que impiden que Trident ofrezca compatibilidad con cada combinación de almacenamiento y controladores.

* Docker Swarm actualmente utiliza el nombre del volumen en lugar del ID de volumen como su identificador de volumen único.
* Las solicitudes de volúmenes se envían simultáneamente a cada nodo de un clúster Swarm.
* Los plugins de volúmenes (incluido Trident) deben ejecutarse de forma independiente en cada nodo de un clúster de Swarm. Debido a la forma en que funciona ONTAP y cómo funcionan los `ontap-nas` controladores y `ontap-san`, son los únicos que pueden operar dentro de estas limitaciones.


El resto de los pilotos están sujetos a problemas como condiciones de carrera que pueden resultar en la creación de un gran número de volúmenes para una sola solicitud sin un claro “ganador”; por ejemplo, Element tiene una característica que permite que los volúmenes tengan el mismo nombre pero diferentes ID.

NetApp ha proporcionado comentarios al equipo de Docker, pero no tiene ningún indicio de recurso futuro.



[[if-a-flexgroup-is-being-provisioned-ontap-does-not-provision-a-second-flexgroup-if-the-second-flexgroup-has-one-or-more-aggregates-in-common-with-the-flexgroup-being-provisioned]]
== Si se está provisionando un FlexGroup, ONTAP no aprovisiona una segunda FlexGroup si el segundo FlexGroup tiene uno o más agregados en común con el FlexGroup que se está aprovisionando.
