---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: trident-rn.html
  versions:
  - name: Astra Trident
    url: "/trident"
    version-number: '23.07'
  - name: Astra Trident
    url: "/trident-2304"
    version-number: '23.04'
  - name: Astra Trident
    url: "/trident-2301"
    version-number: '23.01'
  - name: Astra Trident
    url: "/trident-2210"
    version-number: '22.10'
  - name: Astra Trident
    url: "/trident-2207"
    version-number: '22.07'
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de Astra Trident
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/trident-rn.html"
    - title: Versiones anteriores
      url: "/earlier-versions.html"
  - section: trident-get-started
  - section: trident-install
  - section: trident-use
  - section: trident-managing-k8s
  - section: trident-docker
  - section: trident-reco
  - title: Conocimiento y apoyo
    entries:
    - title: Preguntas frecuentes
      url: "/faq.html"
    - title: Resolución de problemas
      url: "/troubleshooting.html"
    - title: Obtenga ayuda
      url: "/get-help.html"
  - section: trident-reference
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Toda la documentación de Astra
