---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: Puede actualizar fácilmente una instalación existente de Trident con el operador. 
---
= Actualice una instalación de Trident con el operador Trident o Helm
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar Trident mediante el operador Trident manualmente o mediante Helm. Puede actualizar de una instalación del operador de Trident a otra instalación del operador de Trident o actualizar de una `tridentctl` instalación a una versión del operador de Trident. Revise link:upgrade-trident.html#select-an-upgrade-method["Seleccione un método de actualización"] antes de actualizar una instalación del operador Trident.



== Actualizar una instalación manual

Puede actualizar desde una instalación de operador Trident con ámbito de clúster a otra instalación de operador Trident con ámbito de clúster.  Todas las versiones de Trident utilizan un operador con ámbito de clúster.


NOTE: Para actualizar desde Trident que se instaló con el operador de ámbito de espacio de nombres (versiones 20,07 a 20,10), use las instrucciones de actualización de de link:../earlier-versions.html["la versión instalada"]Trident.

.Acerca de esta tarea
Trident proporciona un archivo de paquete que se puede utilizar para instalar el operador y crear objetos asociados para la versión de Kubernetes.

* Para los clústeres que ejecutan Kubernetes 1,24, utilice link:https://github.com/NetApp/trident/tree/stable/v25.02/deploy/bundle_pre_1_25.yaml["bundle_pre_1_25.yaml"^].
* Para los clústeres que ejecutan Kubernetes 1,25 o posterior, utilice link:https://github.com/NetApp/trident/tree/stable/v25.02/deploy/bundle_post_1_25.yaml["bundle_post_1_25.yaml"^].


.Antes de empezar
Asegúrese de que está utilizando un clúster de Kubernetes en ejecución link:../trident-get-started/requirements.html["Una versión de Kubernetes compatible"].

.Pasos
. Compruebe su versión de Trident:
+
[listing]
----
./tridentctl -n trident version
----
. Actualizar el `operator.yaml` , `tridentorchestrator_cr.yaml` , y `post_1_25_bundle.yaml` con el registro y las rutas de imagen de la versión a la que está actualizando (por ejemplo, 25.06) y el secreto correcto.
. Elimine el operador Trident que se utilizó para instalar la instancia actual de Trident .  Por ejemplo, si está actualizando desde la versión 25.02, ejecute el siguiente comando:
+
[listing]
----
kubectl delete -f 25.02.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. Si ha personalizado la instalación inicial mediante `TridentOrchestrator` atributos, puede editar `TridentOrchestrator` objeto para modificar los parámetros de instalación. Esto podría incluir cambios realizados para especificar registros de imágenes de Trident y CSI reflejados para el modo sin conexión, habilitar registros de depuración o especificar secretos de extracción de imágenes.
. Instale Trident utilizando el archivo YAML del paquete correcto para su entorno, donde _<bundle.yaml>_ es
`bundle_pre_1_25.yaml` o `bundle_post_1_25.yaml` basado en su versión de Kubernetes.  Por ejemplo, si está instalando Trident 25.06.0, ejecute el siguiente comando:
+
[listing]
----
kubectl create -f 25.06.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. Edite el torque tridente para incluir la imagen 25.06.0.




== Actualizar una instalación Helm

Puede actualizar una instalación de Trident Helm.


WARNING: Cuando actualice un clúster de Kubernetes de 1,24 a 1,25 o una versión posterior que tiene Trident instalado, debe actualizar los valores.yaml para establecer `excludePodSecurityPolicy` `true` o agregar `--set excludePodSecurityPolicy=true` al `helm upgrade` comando antes de poder actualizar el clúster.

Si ya has actualizado el clúster de Kubernetes de 1,24 a 1,25 sin actualizar el timón de Trident, la actualización de helm fallará. Para que la actualización de HELM se realice, realice estos pasos como requisitos previos:

. Instale el plugin helm-mapkubeapis desde https://github.com/helm/helm-mapkubeapis[].
. Realizar una ejecución en seco para la versión de Trident en el espacio de nombres donde está instalado Trident. Esto enumera los recursos, que se limpiarán.
+
[listing]
----
helm mapkubeapis --dry-run trident  --namespace trident
----
. Realice una carrera completa con el timón para realizar la limpieza.
+
[listing]
----
helm mapkubeapis trident  --namespace trident
----


.Pasos
. Si link:../trident-get-started/kubernetes-deploy-helm.html#deploy-the-trident-operator-and-install-trident-using-helm["Trident instalado usando Helm"]utiliza `helm upgrade trident netapp-trident/trident-operator --version 100.2506.0` para actualizar en un solo paso. Si no ha añadido el repositorio Helm o no puede utilizarlo para actualizar:
+
.. Descargue la versión más reciente de Trident en link:https://github.com/NetApp/trident/releases/latest["La sección _Assets_ de GitHub"^].
.. Utilice el `helm upgrade` comando donde `trident-operator-25.10.0.tgz` refleja la versión a la que desea actualizar.
+
[listing]
----
helm upgrade <name> trident-operator-25.10.0.tgz
----
+

NOTE: Si establece opciones personalizadas durante la instalación inicial (como especificar registros privados reflejados para imágenes de Trident y CSI), agregue la `helm upgrade` comando que utiliza `--set` para asegurarse de que estas opciones están incluidas en el comando upgrade, de lo contrario, los valores se restablecerán a los valores predeterminados.



. Ejecución `helm list` para comprobar que la versión de la gráfica y de la aplicación se han actualizado. Ejecución `tridentctl logs` para revisar cualquier mensaje de depuración.




== Actualizar desde a. `tridentctl` Instalación para el operador Trident

Puede actualizarlo a la versión más reciente del operador de Trident desde un `tridentctl` instalación. Los back-ends y EVs existentes estarán disponibles automáticamente.


NOTE: Antes de cambiar entre los métodos de instalación, revise link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["Moverse entre los métodos de instalación"].

.Pasos
. Descargue la versión más reciente de Trident.
+
[listing]
----
# Download the release required [25.10.0]
mkdir 25.10.0
cd 25.10.0
wget https://github.com/NetApp/trident/releases/download/v25.10.0/trident-installer-25.10.0.tar.gz
tar -xf trident-installer-25.10.0.tar.gz
cd trident-installer
----
. Cree el `tridentorchestrator` CRD del manifiesto.
+
[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
. Despliegue el operador de ámbito de cluster en el mismo espacio de nombres.
+
[listing]
----
kubectl create -f deploy/<bundle-name.yaml>

serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created

#Examine the pods in the Trident namespace
NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-79df798bdc-m79dc   6/6     Running   0          150d
trident-node-linux-xrst8              2/2     Running   0          150d
trident-operator-5574dbbc68-nthjv     1/1     Running   0          1m30s
----
. Cree un `TridentOrchestrator` CR para instalar Trident.
+
[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident

kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

#Examine the pods in the Trident namespace
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-79df798bdc-m79dc        6/6     Running   0          1m
trident-csi-xrst8                   2/2     Running   0          1m
trident-operator-5574dbbc68-nthjv   1/1     Running   0          5m41s
----
. Confirmar que Trident se ha actualizado a la versión prevista.
+
[listing]
----
kubectl describe torc trident | grep Message -A 3

Message:                Trident installed
Namespace:              trident
Status:                 Installed
Version:                v25.10.0
----

