---
sidebar: sidebar 
permalink: trident-use/gcnv.html 
keywords: trident backend, google cloud netapp volumes, nfs volumes, nfs, drivers, access modes, rwo, rwx, rwp, rwop, file system, gke, cloud identity, google cloud 
summary:  
---
= Configura un back-end de Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ahora puede configurar Google Cloud NetApp Volumes como back-end para Trident. Puede adjuntar volúmenes de NFS con un back-end de Google Cloud NetApp Volumes.



== Detalles del controlador de Google Cloud NetApp Volumes

Trident proporciona `google-cloud-netapp-volumes` el controlador para comunicarse con el clúster. Los modos de acceso admitidos son: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Controlador | Protocolo | VolumeMode | Modos de acceso compatibles | Sistemas de archivos compatibles 


| `google-cloud-netapp-volumes`  a| 
NFS
 a| 
Sistema de archivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`

|===


== Identidad de nube para GKE

La identidad de cloud permite a los pods de Kubernetes acceder a los recursos de Google Cloud autenticándose como identidad de carga de trabajo en lugar de proporcionando credenciales explícitas de Google Cloud.

Para aprovechar la identidad de la nube en Google Cloud, debes tener:

* Un clúster de Kubernetes puesto en marcha mediante GKE.
* Identidad de carga de trabajo configurada en el cluster de GKE y el servidor de metadatos de GKE configurado en los pools de nodos.
* Una cuenta de servicio de GCP con el rol NetApp Volumes Admin de Google Cloud (roles/NetApp.admin) o un rol personalizado.
* Trident instalado que incluye el cloudProvider para especificar «GCP» y cloudIdentity especificando la nueva cuenta de servicio de GCP. A continuación se muestra un ejemplo.
+
[role="tabbed-block"]
====
.Operador de Trident
--
Para instalar Trident mediante el operador Trident, edite `tridentorchestrator_cr.yaml` en Establecer `cloudProvider` en `"GCP"` y establezca `cloudIdentity` en `iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com`.

Por ejemplo:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "GCP"
  cloudIdentity: 'iam.gke.io/gcp-service-account: cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com'
----
--
.Timón
--
Establezca los valores para los indicadores *cloud-provider (CP)* y *cloud-identity (CI)* utilizando las siguientes variables de entorno:

`export CP="GCP"`
`export ANNOTATION="iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com"`

En el siguiente ejemplo se instala Trident y se establece `cloudProvider` en GCP mediante la variable de entorno `$CP` y se establece el `cloudIdentity` uso de la variable de entorno `$ANNOTATION` :

[listing]
----
helm install trident trident-operator-100.2406.0.tgz --set cloudProvider=$CP --set cloudIdentity="$ANNOTATION"
----
--
.<code>tridentctl</code>
--
Establezca los valores para los indicadores *cloud provider* y *cloud identity* utilizando las siguientes variables de entorno:

`export CP="GCP"`
`export ANNOTATION="iam.gke.io/gcp-service-account: \cloudvolumes-admin-sa@mygcpproject.iam.gserviceaccount.com"`

En el siguiente ejemplo se instala Trident y se establece el `cloud-provider` indicador en `$CP`, y `cloud-identity` en `$ANNOTATION`:

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$ANNOTATION" -n trident
----
--
====

