---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Al usar Trident con Amazon FSx para NetApp ONTAP, puedes garantizar que los clústeres de Kubernetes que se ejecutan en Amazon Elastic Kubernetes Service (EKS) puedan aprovisionar volúmenes persistentes de bloques y archivos respaldados por ONTAP.' 
---
= Instale Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident optimiza la gestión del almacenamiento de Amazon FSx para NetApp ONTAP en Kubernetes para que sus desarrolladores y administradores se centren en la puesta en marcha de aplicaciones.

Puede instalar Trident mediante uno de los siguientes métodos:

* Timón
* Complemento EKS


Si desea utilizar la funcionalidad Snapshot, instale el complemento del controlador de instantáneas CSI. Consulte link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Habilite la funcionalidad Snapshot para volúmenes CSI"^] si desea obtener más información.



== Instale Trident a través del timón

. Descargue el paquete del instalador de Trident
+
El paquete de instalación de Trident contiene todo lo necesario para implementar el operador Trident e instalar Trident. Descargue y extraiga la última versión del instalador de Trident desde la sección Activos de GitHub.

+
[source, console]
----
wget https://github.com/NetApp/trident/releases/download/v25.02.0/trident-installer-25.02.0.tar.gz
tar -xf trident-installer-25.02.0.tar.gz
cd trident-installer
----
. Establezca los valores para los indicadores *cloud provider* y *cloud identity* utilizando las siguientes variables de entorno:
+
En el siguiente ejemplo se instala Trident y se establece el `cloud-provider` indicador en `$CP`, y `cloud-identity` en `$CI`:

+
[source, console]
----
helm install trident trident-operator-100.2502.0.tgz \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Puede utilizar `helm list` el comando para revisar detalles de instalación como nombre, espacio de nombres, gráfico, estado, versión de la aplicación y número de revisión.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----




== Instale Trident a través del complemento EKS

El complemento Trident EKS incluye los parches de seguridad más recientes, correcciones de errores y está validado por AWS para funcionar con Amazon EKS. El complemento EKS le permite garantizar de forma constante que sus clústeres de Amazon EKS sean seguros y estables y reducir la cantidad de trabajo que necesita para instalar, configurar y actualizar complementos.



=== Requisitos previos

Asegúrese de tener lo siguiente antes de configurar el complemento Trident para AWS EKS:

* Una cuenta de clúster de Amazon EKS con suscripción complementaria
* Permisos de AWS para AWS Marketplace:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Tipo de AMI: Amazon Linux 2 (AL2_x86_64) o Amazon Linux 2 Arm (AL2_ARM_64)
* Tipo de nodo: AMD o ARM
* Un sistema de archivos Amazon FSx para NetApp ONTAP existente




=== Habilite el complemento Trident para AWS

[role="tabbed-block"]
====
.eksctl
--
El siguiente comando de ejemplo instala el complemento Trident EKS:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> \
--service-account-role-arn arn:aws:iam::<account_id>:role/<role_name> --force
----
--
.Consola de gestión
--
. Abra la consola de Amazon EKS en https://console.aws.amazon.com/eks/home#/clusters[].
. En el panel de navegación izquierdo, seleccione *Clusters*.
. Seleccione el nombre del cluster para el que desea configurar el complemento CSI de NetApp Trident.
. Selecciona *Add-ons* y luego selecciona *Get more add-ons*.
. En la página *Select add-ons*, haz lo siguiente:
+
.. En la sección eks-addons de AWS Marketplace, selecciona la casilla de verificación *Trident by NetApp*.
.. Seleccione *Siguiente*.


. En la página de configuración *Configure Selected add-ons*, haga lo siguiente:
+
.. Seleccione la *Versión* que desea usar.
.. Para *Seleccione el rol de IAM*, déjelo en *No establecido*.
.. Siga el esquema de configuración *Add-On* y establezca el parámetro configurationValues en la sección *Valores de configuración* en el Role-arn que creó en el paso anterior (el valor debe tener el siguiente formato `eks.amazonaws.com/role-arn: arn:aws:iam::464262061435:role/AmazonEKS_FSXN_CSI_DriverRole`: ). Si selecciona Sustituir para el método de resolución de conflictos, una o más de las configuraciones del complemento existente se pueden sobrescribir con la configuración del complemento Amazon EKS. Si no habilita esta opción y existe un conflicto con la configuración existente, se producirá un error en la operación. Puede utilizar el mensaje de error resultante para solucionar el conflicto. Antes de seleccionar esta opción, asegúrese de que el complemento de Amazon EKS no gestiona la configuración que necesita para autogestionar.


. Elija *Siguiente*.
. En la página *Revisar y agregar*, selecciona *Crear*.
+
Una vez finalizada la instalación del complemento, verá el complemento instalado.



--
.CLI DE AWS
--
. Cree el `add-on.json` archivo:
+
[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v24.10.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'cloudIdentity: eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----
+

NOTE: Reemplace `<role ARN>` por el ARN del rol que se creó en el paso anterior.

. Instale el complemento Trident EKS.
+
[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----


--
====


=== Actualice el complemento Trident EKS

[role="tabbed-block"]
====
.eksctl
--
* Compruebe la versión actual de su complemento FSxN Trident CSI. Sustituya `my-cluster` por el nombre del clúster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Ejemplo de salida:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v24.10.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Actualice el complemento a la versión devuelta bajo ACTUALIZACIÓN DISPONIBLE en la salida del paso anterior.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v24.10.0-eksbuild.1 --cluster my-cluster --force
----


Si elimina la `--force` opción y cualquiera de las configuraciones del complemento de Amazon EKS entra en conflicto con la configuración existente, la actualización del complemento de Amazon EKS falla; recibirá un mensaje de error que le ayudará a resolver el conflicto. Antes de especificar esta opción, asegúrese de que el complemento de Amazon EKS no gestiona la configuración que debe administrar, ya que dicha configuración se sobrescribe con esta opción. Para obtener más información acerca de otras opciones para esta configuración, consulte link:https://eksctl.io/usage/addons/["Complementos"]. Para obtener más información sobre la gestión de campos de Amazon EKS Kubernetes, consulte link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Gestión del campo de Kubernetes"].

--
.Consola de gestión
--
. Abra la consola de Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[].
. En el panel de navegación izquierdo, seleccione *Clusters*.
. Seleccione el nombre del cluster para el que desea actualizar el complemento CSI de NetApp Trident.
. Seleccione la pestaña *Add-ons*.
. Selecciona *Trident by NetApp* y luego selecciona *Editar*.
. En la página *Configure Trident by NetApp*, haga lo siguiente:
+
.. Seleccione la *Versión* que desea usar.
.. Expanda la *Configuración opcional* y modifique según sea necesario.
.. Seleccione *Guardar cambios*.




--
.CLI DE AWS
--
El siguiente ejemplo actualiza el complemento EKS:

[source, console]
----
aws eks update-addon --cluster-name my-cluster netapp_trident-operator vpc-cni --addon-version v24.10.0-eksbuild.1 \
    --service-account-role-arn <role-ARN> --configuration-values '{}' --resolve-conflicts --preserve
----
--
====


=== Desinstale/elimine el complemento Trident EKS

Tienes dos opciones para eliminar un complemento de Amazon EKS:

* *Preserve el software complementario en su clúster* – Esta opción elimina la administración de Amazon EKS de cualquier configuración. También elimina la posibilidad de que Amazon EKS le notifique las actualizaciones y actualice automáticamente el complemento de Amazon EKS después de iniciar una actualización. Sin embargo, conserva el software complementario en el clúster. Esta opción convierte el complemento en una instalación autogestionada, en lugar de un complemento de Amazon EKS. Con esta opción, no se produce tiempo de inactividad en el complemento. Conserve `--preserve` la opción en el comando para conservar el complemento.
* * Elimine el software complementario completamente de su clúster *: NetApp recomienda eliminar el complemento Amazon EKS de su clúster solo si no hay recursos en su clúster que dependan de él. Elimine `--preserve` la opción del `delete` comando para eliminar el complemento.



NOTE: Si el complemento tiene una cuenta de IAM asociada, la cuenta de IAM no se elimina.

[role="tabbed-block"]
====
.eksctl
--
El siguiente comando desinstala el complemento Trident EKS:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
.Consola de gestión
--
. Abra la consola de Amazon EKS en https://console.aws.amazon.com/eks/home#/clusters[].
. En el panel de navegación izquierdo, seleccione *Clusters*.
. Seleccione el nombre del cluster para el que desea quitar el complemento CSI de NetApp Trident.
. Selecciona la pestaña *Complementos* y luego selecciona *Trident by NetApp*.*
. Seleccione *Quitar*.
. En el cuadro de diálogo *Remove netapp_trident-operator confirmation*, haga lo siguiente:
+
.. Si desea que Amazon EKS deje de administrar la configuración del complemento, seleccione *Conservar en clúster*. Haga esto si desea conservar el software complementario en su clúster para que pueda gestionar todos los ajustes del complemento por su cuenta.
.. Introduzca *netapp_trident-operator*.
.. Seleccione *Quitar*.




--
.CLI DE AWS
--
Reemplace `my-cluster` por el nombre del clúster y, a continuación, ejecute el siguiente comando.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
====