---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imágenes de contenedor requeridas por Trident se almacenan en un registro privado. 
---
= Implementar el operador de Trident con Helm (modo sin conexión)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imágenes de contenedor requeridas por Trident se almacenan en un registro privado. Si no dispone de un registro de imágenes privado, utilice el link:kubernetes-deploy-helm.html["proceso de implementación estándar"].



== Información crítica sobre Trident 25,06

*Debe leer la siguiente información crítica sobre Trident.*

.<strong>Información crítica sobre Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1,33 ahora es compatible con Trident. Actualizar Trident antes de actualizar Kubernetes.
* Trident aplica estrictamente el uso de la configuración de múltiples rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en archivo multipath.conf.
+
Uso de la configuración sin multivía o el uso de `find_multipaths: yes` o. `find_multipaths: smart` el valor del archivo multipath.conf provocará fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versión 21.07.



=====
====


== Despliegue el operador Trident e instale Trident usando Helm

Usando el Tridentlink:https://netapp.github.io/trident-helm-chart["Carta del timón"^] Puede implementar el operador Trident e instalar Trident en un solo paso.

Revisar link:../trident-get-started/kubernetes-deploy.html["descripción general de la instalación"] para asegurarse de cumplir con los requisitos previos de instalación y seleccionar la opción de instalación correcta para el entorno.

.Antes de empezar
Además de la link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["requisitos previos a la implementación"] que necesita link:https://v3.helm.sh/["Versión timón 3"^].


IMPORTANT: Al instalar Trident en un repositorio privado, si está utilizando el `imageRegistry` conmutador para especificar la ubicación del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio.

.Pasos
. Añada el repositorio Helm de Trident:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Utilice `helm install` y especifique un nombre para el despliegue y la ubicación del registro de imágenes. link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Imágenes Trident y CSI"]Puede estar ubicado en un registro o registros diferentes, pero todas las imágenes CSI deben estar ubicadas en el mismo registro. En los ejemplos, `100.2506.0` es la versión de Trident que está instalando.
+
[role="tabbed-block"]
====
.Imágenes en un registro
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.Imágenes en diferentes registros
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.06.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.06 --set tridentImage=<your-registry>/trident:25.06.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Si ya creó un espacio de nombres para Trident, el `--create-namespace` el parámetro no creará un espacio de nombres adicional.



Puede utilizar `helm list` para revisar detalles de la instalación como nombre, espacio de nombres, gráfico, estado, versión de la aplicación, y el número de revisión.



== Pasar los datos de configuración durante la instalación

Existen dos formas de pasar los datos de configuración durante la instalación:

[cols="2"]
|===
| Opción | Descripción 


| `--values` (o. `-f`)  a| 
Especifique un archivo YAML con anulaciones. Esto se puede especificar varias veces y el archivo de la derecha tendrá prioridad.



| `--set`  a| 
Especifique anulaciones en la línea de comandos.

|===
Por ejemplo, para cambiar el valor predeterminado de `debug`, ejecute el siguiente comando donde `100.2506.0` es la versión de Trident que está instalando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----
Para agregar el valor nodePrep, ejecute el siguiente comando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== Opciones de configuración

Esta tabla y la `values.yaml` File, que forma parte del gráfico Helm, proporciona la lista de claves y sus valores predeterminados.


WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplíe la afinidad predeterminada.

[cols="3"]
|===
| Opción | Descripción | Predeterminado 


| `nodeSelector` | Etiquetas de nodo para la asignación de pod |  


| `podAnnotations` | Anotaciones del pod |  


| `deploymentAnnotations` | Anotaciones de despliegue |  


| `tolerations` | Toleraciones para la asignación de POD |  


| `affinity` | Afinidad para la asignación de pod  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplíe la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Descripción de los pods de la controladora y los pods de nodo"] para obtener más detalles. |  


| `tridentControllerPluginTolerations` | Anula la toleración de Kubernetes en pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Descripción de los pods de la controladora y los pods de nodo"] para obtener más detalles. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Descripción de los pods de la controladora y los pods de nodo"] para obtener más detalles. |  


| `tridentNodePluginTolerations` | Anula la toleración de Kubernetes en pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Descripción de los pods de la controladora y los pods de nodo"] para obtener más detalles. |  


| `imageRegistry` | Identifica el registro de `trident-operator` , `trident` y otras imágenes. Déjelo vacío para aceptar el valor predeterminado. IMPORTANTE: Al instalar Trident en un repositorio privado, si está utilizando el `imageRegistry` conmutador para especificar la ubicación del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio. | "" 


| `imagePullPolicy` | Establece la política de extracción de imágenes para el `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Establece los secretos de extracción de imágenes para el `trident-operator`, `trident`, y otras imágenes. |  


| `kubeletDir` | Permite anular la ubicación del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite establecer el nivel de registro del operador Trident en: `trace`, `debug`, `info`, `warn`, `error`, o. `fatal`. | `"info"` 


| `operatorDebug` | Permite configurar en debug el nivel de registro del operador Trident. | `true` 


| `operatorImage` | Permite la sustitución completa de la imagen durante `trident-operator`. | "" 


| `operatorImageTag` | Permite sobrescribir la etiqueta del `trident-operator` imagen. | "" 


| `tridentIPv6` | Permite permitir que Trident funcione en clústeres de IPv6. | `false` 


| `tridentK8sTimeout` | Anula el tiempo de espera predeterminado de 30 segundos para la mayoría de las operaciones de la API de Kubernetes (si no es cero, en segundos). | `0` 


| `tridentHttpRequestTimeout` | Sustituye el timeout por defecto de 90 segundos para las solicitudes HTTP, con `0s` ser una duración infinita para el timeout. No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite deshabilitar la generación de informes periódicos de AutoSupport de Trident. | `false` 


| `tridentAutosupportImageTag` | Permite sobrescribir la etiqueta de la imagen para el contenedor Trident AutoSupport. | `<version>` 


| `tridentAutosupportProxy` | Permite al contenedor Trident AutoSupport llamar a casa a través de un proxy HTTP. | "" 


| `tridentLogFormat` | Define el formato de registro de Trident (`text`o `json`). | `"text"` 


| `tridentDisableAuditLog` | Deshabilita el registrador de auditorías de Trident. | `true` 


| `tridentLogLevel` | Permite definir el nivel de log de Trident en: `trace`, , , , , `debug`, `info` `warn` `error` O `fatal`. | `"info"` 


| `tridentDebug` | Permite establecer el nivel de registro de Trident en `debug`. | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo de Trident específicos para el registro de seguimiento o la supresión de registros. | "" 


| `tridentLogLayers` | Permite activar capas de Trident específicas para el registro de rastreo o la supresión de registros. | "" 


| `tridentImage` | Permite la sustitución completa de la imagen para Trident. | "" 


| `tridentImageTag` | Permite sobrescribir la etiqueta de la imagen para Trident. | "" 


| `tridentProbePort` | Permite sobrescribir el puerto predeterminado utilizado para las sondas de vida/preparación de Kubernetes. | "" 


| `windows` | Permite instalar Trident en el nodo de trabajo de Windows. | `false` 


| `enableForceDetach` | Permite habilitar la función Forzar separación. | `false` 


| `excludePodSecurityPolicy` | Excluye la política de seguridad del pod del operador de la creación. | `false` 


| `nodePrep`  a| 
Permite a Trident preparar los nodos del clúster de Kubernetes para gestionar volúmenes mediante el protocolo de almacenamiento de datos especificado. *Actualmente, `iscsi` es el único valor soportado.*


NOTE: A partir de OpenShift 4.19, la versión mínima de Trident compatible con esta función es 25.06.1.
|  
|===