---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imágenes de contenedor requeridas por Trident no se almacenan en un registro privado. 
---
= Puesta en marcha del operador de Trident con Helm (modo estándar)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imágenes de contenedor requeridas por Trident no se almacenan en un registro privado. Si tiene un registro de imágenes privado, utilice el link:kubernetes-deploy-helm-mirror.html["proceso de puesta en marcha sin conexión"].



== Información crítica sobre Trident 24,10

*Debe leer la siguiente información crítica sobre Trident.*

.<strong>Información crítica sobre Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1,32 ahora es compatible con Trident. Actualizar Trident antes de actualizar Kubernetes.
* Trident aplica estrictamente el uso de la configuración de múltiples rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en archivo multipath.conf.
+
Uso de la configuración sin multivía o el uso de `find_multipaths: yes` o. `find_multipaths: smart` el valor del archivo multipath.conf provocará fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versión 21.07.



=====
====


== Despliegue el operador Trident e instale Trident usando Helm

Usar Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Carta del timón"^] Es posible poner en marcha el operador de Trident e instalar Trident en un paso.

Revisar link:../trident-get-started/kubernetes-deploy.html["descripción general de la instalación"] para asegurarse de cumplir con los requisitos previos de instalación y seleccionar la opción de instalación correcta para el entorno.

.Antes de empezar
Además de la link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["requisitos previos a la implementación"] que necesita link:https://v3.helm.sh/["Versión timón 3"^].

.Pasos
. Añada el repositorio Helm de Trident:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Utilice `helm install` y especifique un nombre para la implementación como en el siguiente ejemplo, donde `100.2404.0` se encuentra la versión de Trident que está instalando.
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2410.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: Si ya creó un espacio de nombres para Trident, el `--create-namespace` el parámetro no creará un espacio de nombres adicional.



Puede utilizar `helm list` para revisar detalles de la instalación como nombre, espacio de nombres, gráfico, estado, versión de la aplicación, y el número de revisión.



== Pasar los datos de configuración durante la instalación

Existen dos formas de pasar los datos de configuración durante la instalación:

[cols="2"]
|===
| Opción | Descripción 


| `--values` (o. `-f`)  a| 
Especifique un archivo YAML con anulaciones. Esto se puede especificar varias veces y el archivo de la derecha tendrá prioridad.



| `--set`  a| 
Especifique anulaciones en la línea de comandos.

|===
Por ejemplo, para cambiar el valor predeterminado de `debug`, ejecute el siguiente comando donde `100.2410.0` es la versión de Trident que está instalando:

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2410.0  --create-namespace --namespace trident --set tridentDebug=true
----


== Opciones de configuración

Esta tabla y la `values.yaml` File, que forma parte del gráfico Helm, proporciona la lista de claves y sus valores predeterminados.

[cols="1,2,3"]
|===
| Opción | Descripción | Predeterminado 


| `nodeSelector` | Etiquetas de nodo para la asignación de pod |  


| `podAnnotations` | Anotaciones del pod |  


| `deploymentAnnotations` | Anotaciones de despliegue |  


| `tolerations` | Toleraciones para la asignación de POD |  


| `affinity` | Afinidad para la asignación de pod  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplíe la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte <<Descripción de los pods de la controladora y los pods de nodo>> para obtener más detalles. |  


| `tridentControllerPluginTolerations` | Anula la toleración de Kubernetes en pods. Consulte <<Descripción de los pods de la controladora y los pods de nodo>> para obtener más detalles. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte <<Descripción de los pods de la controladora y los pods de nodo>> para obtener más detalles. |  


| `tridentNodePluginTolerations` | Anula la toleración de Kubernetes en pods. Consulte <<Descripción de los pods de la controladora y los pods de nodo>> para obtener más detalles. |  


| `imageRegistry` | Identifica el registro de `trident-operator` , `trident` y otras imágenes. Déjelo vacío para aceptar el valor predeterminado. IMPORTANTE: Al instalar Trident en un repositorio privado, si está utilizando el `imageRegistry` conmutador para especificar la ubicación del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio. | `""` 


| `imagePullPolicy` | Establece la política de extracción de imágenes para el `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Establece los secretos de extracción de imágenes para el `trident-operator`, `trident`, y otras imágenes. |  


| `kubeletDir` | Permite anular la ubicación del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite establecer el nivel de registro del operador Trident en: `trace`, `debug`, `info`, `warn`, `error`, o. `fatal`. | `"info"` 


| `operatorDebug` | Permite configurar en debug el nivel de registro del operador Trident. | `true` 


| `operatorImage` | Permite la sustitución completa de la imagen durante `trident-operator`. | `""` 


| `operatorImageTag` | Permite sobrescribir la etiqueta del `trident-operator` imagen. | `""` 


| `tridentIPv6` | Permite permitir que Trident funcione en clústeres de IPv6. | `false` 


| `tridentK8sTimeout` | Anula el tiempo de espera predeterminado de 30 segundos para la mayoría de las operaciones de la API de Kubernetes (si no es cero, en segundos). | `0` 


| `tridentHttpRequestTimeout` | Sustituye el timeout por defecto de 90 segundos para las solicitudes HTTP, con `0s` ser una duración infinita para el timeout. No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite deshabilitar la generación de informes periódicos de AutoSupport de Trident. | `false` 


| `tridentAutosupportImageTag` | Permite sobrescribir la etiqueta de la imagen para el contenedor Trident AutoSupport. | `<version>` 


| `tridentAutosupportProxy` | Permite al contenedor Trident AutoSupport llamar a casa a través de un proxy HTTP. | `""` 


| `tridentLogFormat` | Define el formato de registro de Trident (`text`o `json`). | `"text"` 


| `tridentDisableAuditLog` | Deshabilita el registrador de auditorías de Trident. | `true` 


| `tridentLogLevel` | Permite definir el nivel de log de Trident en: `trace`, , , , , `debug`, `info` `warn` `error` O `fatal`. | `"info"` 


| `tridentDebug` | Permite establecer el nivel de registro de Trident en `debug`. | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo de Trident específicos para el registro de seguimiento o la supresión de registros. | `""` 


| `tridentLogLayers` | Permite activar capas de Trident específicas para el registro de rastreo o la supresión de registros. | `""` 


| `tridentImage` | Permite la sustitución completa de la imagen para Trident. | `""` 


| `tridentImageTag` | Permite sobrescribir la etiqueta de la imagen para Trident. | `""` 


| `tridentProbePort` | Permite sobrescribir el puerto predeterminado utilizado para las sondas de vida/preparación de Kubernetes. | `""` 


| `windows` | Permite instalar Trident en el nodo de trabajo de Windows. | `false` 


| `enableForceDetach` | Permite habilitar la función Forzar separación. | `false` 


| `excludePodSecurityPolicy` | Excluye la política de seguridad del pod del operador de la creación. | `false` 


| `cloudProvider` | Establezca en `"Azure"` Cuando se utilizan identidades gestionadas o una identidad de nube en un clúster de AKS. Establecer en «AWS» cuando se utiliza una identidad de nube en un clúster de EKS. | `""` 


| `cloudIdentity` | Defina la identidad de carga de trabajo («azure.workload.identity/client-id: Xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx») cuando utilice la identidad de cloud en un clúster de AKS. Establezca el rol de AWS IAM ('eks.amazonaws.com/role-arn: arn:aws:iam::123456:ROLE/Trident-ROLE') cuando utilice la identidad de cloud en un clúster de EKS. | `""` 


| `iscsiSelfHealingInterval` | El intervalo en el que se invoca la reparación automática de iSCSI. | `5m0s` 


| `iscsiSelfHealingWaitTime` | La duración después del cual la reparación automática de iSCSI inicia un intento de resolver una sesión obsoleta realizando un cierre de sesión y un inicio de sesión posterior. | `7m0s` 


| `nodePrep` | Permite a Trident preparar los nodos del clúster de Kubernetes para gestionar volúmenes mediante el protocolo de almacenamiento de datos especificado. *Actualmente, `iscsi` es el único valor soportado.* |  
|===


=== Descripción de los pods de la controladora y los pods de nodo

Trident se ejecuta como un pod de controladora único, más un pod de nodo en cada nodo trabajador del clúster. El pod de nodo debe ejecutarse en cualquier host en el que desee potencialmente montar un volumen de Trident.

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["selectores de nodos"^] y.. link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["toleraciones y tintes"^] se utilizan para restringir un pod para ejecutarse en un nodo concreto o preferido. Uso del "ControllerPlugin" y. `NodePlugin`, puede especificar restricciones y anulaciones.

* El complemento de la controladora se ocupa del aprovisionamiento y la gestión de volúmenes, como snapshots y redimensionamiento.
* El complemento de nodo se encarga de conectar el almacenamiento al nodo.

