---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imĂ¡genes de contenedor requeridas por Trident se almacenan en un registro privado. 
---
= Implementar el operador de Trident con Helm (modo sin conexiĂ³n)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imĂ¡genes de contenedor requeridas por Trident se almacenan en un registro privado. Si no dispone de un registro de imĂ¡genes privado, utilice el link:kubernetes-deploy-helm.html["proceso de implementaciĂ³n estĂ¡ndar"].



== InformaciĂ³n crĂ­tica sobre Trident 26.02

*Debe leer la siguiente informaciĂ³n crĂ­tica sobre Trident.*

.<strong>InformaciĂ³n crĂ­tica sobre Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.35 ya es compatible con Trident. Actualiza Trident antes de actualizar Kubernetes.
* Trident aplica estrictamente el uso de la configuraciĂ³n de mĂºltiples rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en archivo multipath.conf.
+
Uso de la configuraciĂ³n sin multivĂ­a o el uso de `find_multipaths: yes` o. `find_multipaths: smart` el valor del archivo multipath.conf provocarĂ¡ fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versiĂ³n 21.07.



=====
====


== Despliegue el operador Trident e instale Trident usando Helm

Usando el Tridentlink:https://netapp.github.io/trident-helm-chart["Carta del timĂ³n"^] Puede implementar el operador Trident e instalar Trident en un solo paso.

Revisar link:../trident-get-started/kubernetes-deploy.html["descripciĂ³n general de la instalaciĂ³n"] para asegurarse de cumplir con los requisitos previos de instalaciĂ³n y seleccionar la opciĂ³n de instalaciĂ³n correcta para el entorno.

.Antes de empezar
AdemĂ¡s de la link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["requisitos previos a la implementaciĂ³n"] que necesita link:https://v3.helm.sh/["VersiĂ³n timĂ³n 3"^].


IMPORTANT: Al instalar Trident en un repositorio privado, si estĂ¡ utilizando el `imageRegistry` conmutador para especificar la ubicaciĂ³n del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio.

.Pasos
. AĂ±ada el repositorio Helm de Trident:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Usa `helm install` y especifica un nombre para tu deployment y la ubicaciĂ³n del image registry. Tu link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["ImĂ¡genes Trident y CSI"] puede estar en un registro o en registros diferentes, pero todas las imĂ¡genes CSI deben estar en el mismo registro. En los ejemplos, `100.2602.0` es la versiĂ³n de Trident que estĂ¡s instalando.
+
[role="tabbed-block"]
====
.ImĂ¡genes en un registro
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2602.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.ImĂ¡genes en diferentes registros
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2602.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:26.02.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:26.02 --set tridentImage=<your-registry>/trident:26.02.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Si ya creĂ³ un espacio de nombres para Trident, el `--create-namespace` el parĂ¡metro no crearĂ¡ un espacio de nombres adicional.



Puede utilizar `helm list` para revisar detalles de la instalaciĂ³n como nombre, espacio de nombres, grĂ¡fico, estado, versiĂ³n de la aplicaciĂ³n, y el nĂºmero de revisiĂ³n.



== Pasar los datos de configuraciĂ³n durante la instalaciĂ³n

Existen dos formas de pasar los datos de configuraciĂ³n durante la instalaciĂ³n:

[cols="2"]
|===
| OpciĂ³n | DescripciĂ³n 


| `--values` (o. `-f`)  a| 
Especifique un archivo YAML con anulaciones. Esto se puede especificar varias veces y el archivo de la derecha tendrĂ¡ prioridad.



| `--set`  a| 
Especifique anulaciones en la lĂ­nea de comandos.

|===
Por ejemplo, para cambiar el valor por defecto de `debug`, ejecuta el siguiente comando donde `100.2602.0` es la versiĂ³n de Trident que estĂ¡s instalando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2602.0  --create-namespace --namespace trident --set tridentDebug=true
----
Para agregar el valor nodePrep, ejecute el siguiente comando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2602.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== Opciones de configuraciĂ³n

Esta tabla y la `values.yaml` File, que forma parte del grĂ¡fico Helm, proporciona la lista de claves y sus valores predeterminados.


WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplĂ­e la afinidad predeterminada.

[cols="3"]
|===
| OpciĂ³n | DescripciĂ³n | Predeterminado 


| `nodeSelector` | Etiquetas de nodo para la asignaciĂ³n de pod |  


| `podAnnotations` | Anotaciones del pod |  


| `deploymentAnnotations` | Anotaciones de despliegue |  


| `tolerations` | Toleraciones para la asignaciĂ³n de POD |  


| `affinity` | Afinidad para la asignaciĂ³n de pod  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplĂ­e la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s detalles. |  


| `tridentControllerPluginTolerations` | Anula la toleraciĂ³n de Kubernetes en pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s detalles. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s detalles. |  


| `tridentNodePluginTolerations` | Anula la toleraciĂ³n de Kubernetes en pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s detalles. |  


| `imageRegistry` | Identifica el registro de `trident-operator` , `trident` y otras imĂ¡genes. DĂ©jelo vacĂ­o para aceptar el valor predeterminado. IMPORTANTE: Al instalar Trident en un repositorio privado, si estĂ¡ utilizando el `imageRegistry` conmutador para especificar la ubicaciĂ³n del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio. | "" 


| `imagePullPolicy` | Establece la polĂ­tica de extracciĂ³n de imĂ¡genes para el `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Establece los secretos de extracciĂ³n de imĂ¡genes para el `trident-operator`, `trident`, y otras imĂ¡genes. |  


| `kubeletDir` | Permite anular la ubicaciĂ³n del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite establecer el nivel de registro del operador Trident en: `trace`, `debug`, `info`, `warn`, `error`, o. `fatal`. | `"info"` 


| `operatorDebug` | Permite configurar en debug el nivel de registro del operador Trident. | `true` 


| `operatorImage` | Permite la sustituciĂ³n completa de la imagen durante `trident-operator`. | "" 


| `operatorImageTag` | Permite sobrescribir la etiqueta del `trident-operator` imagen. | "" 


| `tridentIPv6` | Permite permitir que Trident funcione en clĂºsteres de IPv6. | `false` 


| `tridentK8sTimeout`  a| 
Anula el tiempo de espera predeterminado de 180 segundos para la mayorĂ­a de las operaciones de API de Kubernetes (si es distinto de cero, en segundos).


NOTE: El `tridentK8sTimeout` El parĂ¡metro solo se aplica a la instalaciĂ³n de Trident .
| `180` 


| `tridentHttpRequestTimeout` | Sustituye el timeout por defecto de 90 segundos para las solicitudes HTTP, con `0s` ser una duraciĂ³n infinita para el timeout. No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite deshabilitar la generaciĂ³n de informes periĂ³dicos de AutoSupport de Trident. | `false` 


| `tridentAutosupportImageTag` | Permite sobrescribir la etiqueta de la imagen para el contenedor Trident AutoSupport. | `<version>` 


| `tridentAutosupportProxy` | Permite al contenedor Trident AutoSupport llamar a casa a travĂ©s de un proxy HTTP. | "" 


| `tridentLogFormat` | Define el formato de registro de Trident (`text`o `json`). | `"text"` 


| `tridentDisableAuditLog` | Deshabilita el registrador de auditorĂ­as de Trident. | `true` 


| `tridentLogLevel` | Permite definir el nivel de log de Trident en: `trace`, , , , , `debug`, `info` `warn` `error` O `fatal`. | `"info"` 


| `tridentDebug` | Permite establecer el nivel de registro de Trident en `debug`. | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo de Trident especĂ­ficos para el registro de seguimiento o la supresiĂ³n de registros. | "" 


| `tridentLogLayers` | Permite activar capas de Trident especĂ­ficas para el registro de rastreo o la supresiĂ³n de registros. | "" 


| `tridentImage` | Permite la sustituciĂ³n completa de la imagen para Trident. | "" 


| `tridentImageTag` | Permite sobrescribir la etiqueta de la imagen para Trident. | "" 


| `tridentProbePort` | Permite sobrescribir el puerto predeterminado utilizado para las sondas de vida/preparaciĂ³n de Kubernetes. | "" 


| `windows` | Permite instalar Trident en el nodo de trabajo de Windows. | `false` 


| `enableForceDetach` | Permite activar la funciĂ³n de desconexiĂ³n forzada. Puede automatizar el proceso de desconexiĂ³n forzada mediante la integraciĂ³n con el operador de comprobaciĂ³n del estado del nodo (NHC). Para obtener mĂ¡s informaciĂ³n, consultelink:../trident-reco/force-detach.html["AutomatizaciĂ³n de la conmutaciĂ³n por error de aplicaciones con estado con Trident"] . | `false` 


| `excludePodSecurityPolicy` | Excluye la polĂ­tica de seguridad del pod del operador de la creaciĂ³n. | `false` 


| `nodePrep`  a| 
Permite a Trident preparar los nodos del clĂºster de Kubernetes para gestionar volĂºmenes mediante el protocolo de almacenamiento de datos especificado. *Actualmente, `iscsi` es el Ăºnico valor soportado.*


NOTE: A partir de OpenShift 4.19, la versiĂ³n mĂ­nima de Trident compatible con esta funciĂ³n es 25.06.1.
|  


| `resources`  a| 
Establece los lĂ­mites de recursos y las solicitudes de Kubernetes para los pods del controlador, nodo y operador de Trident . Puedes configurar la CPU y la memoria para cada contenedor y sidecar para gestionar la asignaciĂ³n de recursos en Kubernetes.

Para obtener mĂ¡s informaciĂ³n sobre la configuraciĂ³n de solicitudes y lĂ­mites de recursos, consultelink:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["GestiĂ³n de recursos para pods y contenedores"^] .

[WARNING]
====
* NO cambie los nombres de ningĂºn contenedor ni campo.
* NO cambie la sangrĂ­a: la sangrĂ­a de YAML es fundamental para un anĂ¡lisis correcto.


====
[NOTE]
====
* Por defecto no se aplican lĂ­mites; solo las solicitudes tienen valores predeterminados.
* Los nombres de los contenedores se enumeran tal como aparecen en las especificaciones del pod.
* Los sidecares se enumeran debajo de cada contenedor principal.
* Consulta el TORC `status.CurrentInstallationParams` campo para ver los valores aplicados actualmente.


==== a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----
|===