---
sidebar: sidebar 
permalink: trident-get-started/k8s-netapp.html 
keywords: kubernetes, netapp storage, ontap, cloud volumes ontap, santricity, element software, netapp hci, anf, azure netapp files, aws, amazon fsx 
summary: La cartera de productos de almacenamiento de NetApp se integra con muchos aspectos diferentes de un clúster de Kubernetes, por lo que proporciona funcionalidades de gestión de datos avanzadas que mejoran la funcionalidad, la funcionalidad, el rendimiento y la disponibilidad de la puesta en marcha de Kubernetes. 
---
= Integración de Kubernetes con productos de NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La cartera de productos de almacenamiento de NetApp se integra con muchos aspectos diferentes de un clúster de Kubernetes, por lo que proporciona funcionalidades de gestión de datos avanzadas que mejoran la funcionalidad, la funcionalidad, el rendimiento y la disponibilidad de la puesta en marcha de Kubernetes.



== Trident

https://docs.netapp.com/us-en/trident/["Trident"^] Facilita a las empresas la gestión, la protección y el traslado de sus cargas de trabajo en contenedores ricas en datos que se ejecutan en Kubernetes dentro de los clouds públicos y en las instalaciones. Trident aprovisiona y proporciona almacenamiento en contenedores persistente mediante Trident de la cartera de almacenamiento NetApp demostrada y expansiva en el cloud público y en las instalaciones. También ofrece un conjunto amplio de funcionalidades avanzadas de gestión de datos para aplicaciones, como snapshots, backups y restauración, registros de actividades y clonado activo para la protección de datos, recuperación ante desastres/datos, auditoría de datos y casos de uso de migración para cargas de trabajo de Kubernetes.



== ONTAP

ONTAP es el sistema operativo de almacenamiento unificado y multiprotocolo de NetApp que ofrece funcionalidades avanzadas de gestión de datos para cualquier aplicación. Los sistemas ONTAP tienen configuraciones all-flash, híbridas o all-HDD y ofrecen muchos modelos de puesta en marcha diferentes, como hardware a medida (FAS y AFF), unidad genérica (ONTAP Select) y solo cloud (Cloud Volumes ONTAP).


NOTE: Trident es compatible con todos los modelos de puesta en marcha de ONTAP mencionados anteriormente.



== Cloud Volumes ONTAP

Cloud Volumes ONTAP es un dispositivo de almacenamiento exclusivamente de software que ejecuta el software de gestión de datos ONTAP en la nube. Puedes usar Cloud Volumes ONTAP para cargas de trabajo de producción, recuperación ante desastres, DevOps, recursos compartidos de archivos y gestión de bases de datos. Extiende el almacenamiento empresarial a la nube al ofrecer eficiencias de almacenamiento, alta disponibilidad, replicación de datos, organización de datos por niveles y consistencia de aplicaciones.



== Amazon FSX para ONTAP de NetApp

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX para ONTAP de NetApp"^] Es un servicio AWS totalmente gestionado que le permite iniciar y ejecutar sistemas de archivos con tecnología del sistema operativo de almacenamiento NetApp ONTAP. FSX para ONTAP te permite aprovechar las funciones, el rendimiento y las funcionalidades administrativas de NetApp que ya conoces, a la vez que aprovechas la simplicidad, la agilidad, la seguridad y la escalabilidad de almacenar datos en AWS. FSX para ONTAP es compatible con muchas de las funciones del sistema de archivos ONTAP y las API de administración.



== Software Element

https://www.netapp.com/data-management/element-software/["Elemento"^] permite al administrador de almacenamiento consolidar cargas de trabajo garantizando el rendimiento y haciendo posible un espacio de almacenamiento simplificado y optimizado. Junto con una API para permitir la automatización de todos los aspectos de la gestión del almacenamiento, Element permite a los administradores de almacenamiento hacer más con menos esfuerzo.



== NetApp HCI

https://www.netapp.com/virtual-desktop-infrastructure/netapp-hci/["NetApp HCI"^] simplifica la gestión y el escalado del centro de datos mediante la automatización de las tareas rutinarias y permite que los administradores de la infraestructura se centren en funciones más importantes.

Trident es totalmente compatible con NetApp HCI. Trident puede aprovisionar y gestionar dispositivos de almacenamiento para aplicaciones en contenedores directamente en la plataforma de almacenamiento subyacente de NetApp HCI.



== Azure NetApp Files

https://azure.microsoft.com/en-us/products/netapp/["Azure NetApp Files"^] es un servicio para compartir archivos de clase empresarial de Azure, impulsado por NetApp. Puedes ejecutar tus cargas de trabajo basadas en archivos más exigentes en Azure de forma nativa, con el rendimiento y la gestión de datos avanzada que esperas de NetApp.



== NetApp Volumes para Google Cloud

https://www.netapp.com/google-cloud/netapp-volumes/["NetApp Volumes para Google Cloud"^] es un servicio de archivos nativo de la nube que proporciona volúmenes NAS a través de NFS con rendimiento all-flash. Este servicio permite que cualquier carga de trabajo, incluidas las aplicaciones heredadas, se ejecute en la nube de GCP. Ofrece un servicio totalmente gestionado que proporciona un alto rendimiento constante, clonación instantánea, protección de datos y acceso seguro a las instancias de Google Compute Engine (GCE).
