---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Antes de instalar Trident, debe revisar estos requisitos generales del sistema. Es posible que los back-ends específicos tengan requisitos adicionales. 
---
= Requisitos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar Trident, debe revisar estos requisitos generales del sistema. Es posible que los back-ends específicos tengan requisitos adicionales.



== Información crítica sobre Trident

*Debe leer la siguiente información crítica sobre Trident.*

.<strong>Información crítica sobre Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.36 ya es compatible con Trident. Actualiza Trident antes de actualizar Kubernetes.
* Trident aplica estrictamente el uso de la configuración de múltiples rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en archivo multipath.conf.
+
Uso de la configuración sin multivía o el uso de `find_multipaths: yes` o. `find_multipaths: smart` el valor del archivo multipath.conf provocará fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versión 21.07.



=====
====


== Front-ends compatibles (orquestadores)

Trident admite varios motores de contenedor y orquestadores, entre los que se incluyen los siguientes:

* Anthos on-premises (VMware) y Anthos en 1,16 básico
* Kubernetes 1.27 - 1.36
* OpenShift 4.12, 4.14 - 4.22 (si planeas usar la preparación de nodos iSCSI con OpenShift 4.19, la versión mínima de Trident compatible es 25.06.1.)
+

NOTE: Trident continúa brindando soporte para versiones anteriores de OpenShift en consonancia con lalink:https://access.redhat.com/support/policy/updates/openshift["Ciclo de vida de lanzamiento de Red Hat Extended Update Support (EUS)"] , incluso si dependen de versiones de Kubernetes que ya no reciben soporte oficial.  Al instalar Trident en estos casos, puede ignorar con seguridad cualquier mensaje de advertencia sobre la versión de Kubernetes.

* Rancher Kubernetes Engine 2 (RKE2) v1.28.x - 1.36.x


Trident también funciona con una gran cantidad de ofertas de Kubernetes totalmente gestionadas y autogestionadas, como Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Mirantis Kubernetes Engine (MKE) y la cartera de VMware Tanzu.

Trident y ONTAP se pueden utilizar como proveedor de almacenamiento paralink:https://kubevirt.io/["Virt de KubeVirt"].


WARNING: Antes de actualizar un clúster de Kubernetes de la versión 1,25 a la versión 1,26 o una versión posterior que tenga instalado Trident, consulte link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Actualizar una instalación Helm"].



== Back-ends compatibles (almacenamiento)

Para utilizar Trident, se necesitan uno o varios de los siguientes back-ends admitidos:

* Amazon FSX para ONTAP de NetApp
* Azure NetApp Files
* Cloud Volumes ONTAP
* NetApp Volumes para Google Cloud
* Cabina All SAN de NetApp (ASA)
* FAS, AFF o ASA r2 locales (iSCSI, NVMe/TCP y FC) que ejecutan versiones de ONTAP con soporte total o limitado de NetApp . Ver link:https://mysupport.netapp.com/site/info/version-support["Compatibilidad con versiones de software"].
* Software HCI/Element de NetApp 11 o posterior




== Compatibilidad de Trident con KubeVirt y OpenShift Virtualization

.Controladores de almacenamiento compatibles:
Trident admite los siguientes controladores de ONTAP para KubeVirt y OpenShift Virtualization:

* ontap-nas
* ONTAP-san (iSCSI, FCP, NVMe sobre TCP)
* Economía ONTAP-san (solo iSCSI)


.Puntos que se deben tener en cuenta:
* Actualice la clase de almacenamiento para tener el `fsType` parámetro (por ejemplo `fsType: "ext4"`: ) En el entorno de virtualización OpenShift. Si es necesario, configure el modo de volumen para bloquear explícitamente mediante el `volumeMode=Block` parámetro de `dataVolumeTemplates` para notificar a CDI que cree volúmenes de datos de bloque.
* _RWX modo de acceso para controladores de almacenamiento en bloque_: Los controladores ONTAP-san (iSCSI, NVMe/TCP, FC) y ONTAP-san-economy (iSCSI) solo se admiten con «volumeMode: Block» (dispositivo sin procesar). Para estos controladores, no se puede utilizar el `fstype` parámetro porque los volúmenes se proporcionan en modo de dispositivo raw.
* Para flujos de trabajo de migración en tiempo real en los que se requiere el modo de acceso RWX, se admiten estas combinaciones:
+
** NFS + `volumeMode=Filesystem`
** ISCSI + `volumeMode=Block` (dispositivo sin formato)
** NVMe/TCP + `volumeMode=Block` (dispositivo sin configurar)
** FC `volumeMode=Block` + (dispositivo bruto)






== Compatibilidad de Trident con Kubernetes en Kubernetes y con los planos de control alojados en OpenShift

A partir de la versión 26.06, Trident califica completamente la topología de Kubernetes on Kubernetes. Clústeres de Kubernetes cuyos nodos se ejecutan como máquinas virtuales KubeVirt en un clúster de infraestructura (host). Esta topología respalda ofertas de planos de control alojados como los hosted control planes (HCP) de OpenShift en OpenShift Virtualization.


NOTE: Esta configuración funcionaba en versiones anteriores, pero la certificación completa comienza con la 26.06.

El clúster invitado (inquilino) utiliza el controlador CSI KubeVirt (`kubevirt-csi` como proveedor de almacenamiento. Cuando una carga de trabajo en el clúster invitado solicita un `PersistentVolumeClaim`, el controlador CSI KubeVirt crea un volumen correspondiente en el clúster de infraestructura. Trident aprovisiona el volumen desde ONTAP y el volumen se conecta en caliente a la VM del nodo invitado. Trident solo se ejecuta en el clúster de infraestructura. El clúster invitado consume almacenamiento ONTAP de forma indirecta a través del controlador CSI KubeVirt.

.Requisitos:
* Trident se instala en el clúster de infraestructura con un backend ONTAP compatible.
* En el clúster de infraestructura existe una clase de almacenamiento Trident para que el controlador CSI de KubeVirt pueda asignar los volúmenes del clúster de invitados.
* KubeVirt o OpenShift Virtualization se implementa en el clúster de infraestructura, y el controlador CSI KubeVirt se instala en cada clúster invitado.


[cols="2,1"]
|===
| Componente | Versión 


| Trident | 26,06 


| Kubernetes (infraestructura y clúster invitado) | 1,36 


| Virt de KubeVirt | 1.9.0-beta.0 


| Importador de datos en contenedores (CDI) | 1,65 
|===
.Puntos que se deben tener en cuenta:
* En el clúster invitado, los volúmenes aparecen como dispositivos de bloque conectados en caliente en las máquinas virtuales del nodo invitado.
* El flujo de trabajo del controlador CSI de KubeVirt no requiere Trident en el clúster invitado. Configuras el backend de ONTAP y la clase de almacenamiento en el clúster de infraestructura.


.Instala Trident directamente en el clúster invitado:
También puedes instalar Trident directamente en el clúster invitado (inquilino). Instala Trident en el clúster invitado cuando necesites el conjunto completo de funciones de Trident, como instantáneas, clones, cambio de tamaño de volúmenes e importación, que `kubevirt-csi` no ofrece por sí solo.

En el clúster de invitados, utiliza protocolos basados en IP: NFS, iSCSI y NVMe/TCP. El clúster de invitados no es compatible con Fibre Channel (FC) porque los nodos de invitados son máquinas virtuales sin conectividad FC directa.



== Requisitos de funciones

En la tabla siguiente se resumen las funciones disponibles con este lanzamiento de Trident y las versiones de Kubernetes compatibles.

[cols="3"]
|===
| Función | La versión de Kubernetes | ¿Se requieren puertas de funciones? 


| Trident  a| 
1.27 - 1.36
 a| 
No



| Snapshots de volumen  a| 
1.27 - 1.36
 a| 
No



| RVP desde snapshots de volumen  a| 
1.27 - 1.36
 a| 
No



| Cambio de tamaño del VP de iSCSI  a| 
1.27 - 1.36
 a| 
No



| CHAP bidireccional de ONTAP  a| 
1.27 - 1.36
 a| 
No



| Políticas de exportación dinámicas  a| 
1.27 - 1.36
 a| 
No



| Operador de Trident  a| 
1.27 - 1.36
 a| 
No



| Topología CSI  a| 
1.27 - 1.36
 a| 
No

|===


== Se probaron sistemas operativos host

Aunque Trident no admite oficialmente sistemas operativos específicos, se sabe que los siguientes funcionan:

* Versiones de Red Hat Enterprise Linux CoreOS (RHCOS) compatibles con OpenShift Container Platform en AMD64 y ARM64
* Red Hat Enterprise Linux (RHEL) 8 o posterior en AMD64 y ARM64
+

NOTE: NVMe/TCP requiere RHEL 9 o posterior.

* Ubuntu 22.04 LTS o posterior en AMD64 y ARM64
* Windows Server 2022
* SUSE Linux Enterprise Server (SLES) 15 o posterior


De forma predeterminada, Trident se ejecuta en un contenedor y, por lo tanto, se ejecuta en cualquier trabajador Linux. Sin embargo, estos trabajadores deben poder montar los volúmenes que proporciona Trident con el cliente NFS estándar o el iniciador de iSCSI, en función de los back-ends que utilice.

La `tridentctl` Utility también se ejecuta en cualquiera de estas distribuciones de Linux.



== Configuración de hosts

Todos los nodos de trabajadores del clúster de Kubernetes deben poder montar los volúmenes que haya aprovisionado para los pods. Para preparar los nodos de trabajo, debe instalar las herramientas NFS, iSCSI o NVMe según la selección de controladores.

link:../trident-use/worker-node-prep.html["Prepare el nodo de trabajo"]



== Configuración del sistema de almacenamiento

Es posible que Trident requiera cambios en un sistema de almacenamiento antes de que la configuración de back-end pueda utilizarlo.

link:../trident-use/backends.html["Configurar los back-ends"]



== Puertos Trident

Trident requiere acceso a puertos específicos para la comunicación.

link:../trident-reference/ports.html["Puertos Trident"]



== Imágenes de contenedor y las versiones de Kubernetes correspondientes

En el caso de instalaciones de aire acondicionado, la siguiente lista es una referencia de las imágenes de contenedores necesarias para instalar Trident. Utilice `tridentctl images` el comando para verificar la lista de imágenes de contenedor necesarias.



=== Imágenes de contenedor requeridas para Trident 26.02

[cols="2"]
|===
| Versiones de Kubernetes | Imagen de contenedor 


| v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.34.0, v1.35.0, v1.36.0  a| 
* docker.io/netapp/trident:26.02.0
* docker.io/netapp/trident-autosupport:26.02
* registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
* registro.k8s.io/sig-storage/csi-attacher:v4.10.0
* registry.k8s.io/sig-storage/csi-resizer:v2.0.0
* registry.k8s.io/sig-storage/csi-snapshotter:v8.5.0
* registro.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
* docker.io/netapp/trident-operator:26.02.0 (opcional)


|===