---
sidebar: sidebar 
permalink: trident-concepts/snapshots.html 
keywords: provisioning, Trident 
summary: Obtenga más información sobre cómo Trident maneja la creación de snapshots de volúmenes para sus controladores. 
---
= Copias de Snapshot de volumen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga más información sobre cómo Trident maneja la creación de snapshots de volúmenes para sus controladores.



== Obtenga información acerca de la creación de snapshots de volúmenes

* Para la `ontap-nas`, `ontap-san`, `gcp-cvs`, y. `azure-netapp-files` Controladores, cada volumen persistente (PV) se asigna a una FlexVol. Como resultado, las copias de Snapshot de volumen se crean como copias de Snapshot de NetApp. La tecnología Snapshot de NetApp ofrece una mayor estabilidad, escalabilidad, capacidad de recuperación y rendimiento que la tecnología snapshot de la competencia. Estas copias Snapshot son extremadamente eficientes, tanto en el tiempo necesario para crearlas como en el espacio de almacenamiento.
* Para la `ontap-nas-flexgroup` Cada controlador, cada volumen persistente (PV) se asigna a una FlexGroup. Como resultado, las copias de Snapshot de volumen se crean como copias de Snapshot de FlexGroup de NetApp. La tecnología Snapshot de NetApp ofrece una mayor estabilidad, escalabilidad, capacidad de recuperación y rendimiento que la tecnología snapshot de la competencia. Estas copias Snapshot son extremadamente eficientes, tanto en el tiempo necesario para crearlas como en el espacio de almacenamiento.
* Para la `ontap-san-economy` Controlador, VP se asigna a las LUN creadas en los FlexVols compartidos. Las copias Snapshot Volumede VP realizan FlexClones del LUN asociado. La tecnología FlexClone de ONTAP permite crear copias de incluso los conjuntos de datos más grandes casi al instante. Las copias comparten bloques de datos con sus padres, sin consumir almacenamiento, excepto lo que se necesita para los metadatos.
* Para la `solidfire-san` Cada controlador, cada VP asigna una LUN creada en el software NetApp Element/clúster HCI de NetApp. Las copias Snapshot de volumen están representadas por copias Snapshot de Element de la LUN subyacente. Estas copias Snapshot son copias puntuales y solo ocupan una pequeña cantidad de recursos y espacio del sistema.
* Cuando trabajan con los `ontap-nas` controladores y `ontap-san`, las copias Snapshot de ONTAP son copias puntuales de la FlexVol y consumen espacio en la propia FlexVol. Esto puede dar como resultado la cantidad de espacio editable en el volumen para reducirlo con el tiempo a medida que se crean y se programan las copias Snapshot. Una forma sencilla de abordar esto es aumentar el volumen mediante el cambio de tamaño a través de Kubernetes. Otra opción es eliminar las snapshots que ya no son necesarias. Cuando se elimina una snapshot de volumen creada mediante Kubernetes, Trident elimina la snapshot de ONTAP asociada. También se pueden eliminar las copias de Snapshot de ONTAP que no se crearon con Kubernetes.


Con Trident, puede usar VolumeSnapshots para crear nuevos VP a partir de ellos. La creación de VP a partir de estas snapshots se realiza usando la tecnología FlexClone para los back-ends de ONTAP y CVS compatibles. Cuando se crea un volumen persistente a partir de una copia Snapshot, el volumen de backup es FlexClone del volumen principal de la copia Snapshot.  `solidfire-san`El controlador usa clones de volúmenes del software Element para crear VP a partir de snapshots. Aquí se crea un clon a partir de la copia de Snapshot de Element.
