---
sidebar: sidebar 
permalink: trident-protect/learn-about-trident-protect.html 
keywords: overview, concepts, features, use case, workloads, how workload factory works 
summary: Trident Protect le permite proteger sus aplicaciones y datos de aplicaciones utilizando Trident. 
---
= Obtenga más información sobre Trident Protect
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Trident Protect proporciona capacidades avanzadas de gestión de datos de aplicaciones que mejoran la funcionalidad y la disponibilidad de las aplicaciones Kubernetes con estado respaldadas por los sistemas de almacenamiento NetApp ONTAP y el aprovisionador de almacenamiento NetApp Trident CSI.  Trident Protect simplifica la gestión, la protección y el movimiento de cargas de trabajo en contenedores en nubes públicas y entornos locales. También ofrece capacidades de automatización a través de su API y CLI.

Puede proteger aplicaciones con Trident Protect creando recursos personalizados (CR) o utilizando la CLI de Trident Protect.



== El futuro

Puede obtener información sobre los requisitos de Trident Protect antes de instalarlo:

* link:trident-protect-requirements.html["Requisitos de Trident Protect"]

