---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Si su entorno cumple con los requisitos, puede seguir estos pasos para instalar Trident Protect. 
---
= Instalar y configurar Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si su entorno cumple con los requisitos de Trident Protect, puede seguir estos pasos para instalar Trident Protect en su clúster.  Puede obtener Trident Protect de NetApp o instalarlo desde su propio registro privado. Instalar desde un registro privado resulta útil si su clúster no puede acceder a Internet.



== Instalar Trident Protect

[role="tabbed-block"]
====
.Instalar Trident Protect de NetApp
--
.Pasos
. Añada el repositorio Helm de Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Utilice Helm para instalar Trident Protect. Reemplazar `<name-of-cluster>` con un nombre de clúster, que se asignará al clúster y se utilizará para identificar las copias de seguridad y las instantáneas del clúster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2510.0 --create-namespace --namespace trident-protect
----
. Opcionalmente, para habilitar el registro de depuración (recomendado para la resolución de problemas), utilice:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect
----
+
El registro de depuración ayuda al soporte de NetApp a solucionar problemas sin necesidad de cambiar el nivel de registro ni reproducir el problema.



--
.Instalar Trident Protect desde un registro privado
--
Puede instalar Trident Protect desde un registro de imágenes privado si su clúster de Kubernetes no puede acceder a Internet. En estos ejemplos, sustituya los valores entre corchetes por información de su entorno:

.Pasos
. Tire de las siguientes imágenes a su máquina local, actualice las etiquetas y, a continuación, empújelas en su registro privado:
+
[source, console]
----
docker.io/netapp/controller:25.10.0
docker.io/netapp/restic:25.10.0
docker.io/netapp/kopia:25.10.0
docker.io/netapp/kopiablockrestore:25.10.0
docker.io/netapp/trident-autosupport:25.10.0
docker.io/netapp/exechook:25.10.0
docker.io/netapp/resourcebackup:25.10.0
docker.io/netapp/resourcerestore:25.10.0
docker.io/netapp/resourcedelete:25.10.0
docker.io/netapp/trident-protect-utils:v1.0.0
----
+
Por ejemplo:

+
[source, console]
----
docker pull docker.io/netapp/controller:25.10.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.10.0 <private-registry-url>/controller:25.10.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.10.0
----
+

NOTE: Para obtener el gráfico de Helm, primero descárguelo en una máquina con acceso a Internet usando `helm pull trident-protect --version 100.2510.0 --repo https://netapp.github.io/trident-protect-helm-chart`, luego copie el resultado `trident-protect-100.2510.0.tgz` transfiera el archivo a su entorno sin conexión e instálelo usando `helm install trident-protect ./trident-protect-100.2510.0.tgz` en lugar de la referencia al repositorio en el paso final.

. Cree el espacio de nombres del sistema Trident Protect:
+
[source, console]
----
kubectl create ns trident-protect
----
. Inicie sesión en el Registro:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Cree un secreto de extracción para utilizarlo en la autenticación del registro privado:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Añada el repositorio Helm de Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Crea un archivo llamado `protectValues.yaml` . Asegúrese de que contenga las siguientes configuraciones de Trident Protect:
+
[source, yaml]
----
---
imageRegistry: <private-registry-url>
imagePullSecrets:
  - name: regcred
----
+

NOTE: El `imageRegistry` y `imagePullSecrets` Los valores se aplican a todas las imágenes de componentes, incluyendo `resourcebackup` y `resourcerestore` . Si envías imágenes a una ruta de repositorio específica dentro de tu registro (por ejemplo, `example.com:443/my-repo`), incluya la ruta completa en el campo del registro. Esto garantizará que todas las imágenes se extraigan de `<private-registry-url>/<image-name>:<tag>`.

. Utilice Helm para instalar Trident Protect. Reemplazar `<name_of_cluster>` con un nombre de clúster, que se asignará al clúster y se utilizará para identificar las copias de seguridad y las instantáneas del clúster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
. Opcionalmente, para habilitar el registro de depuración (recomendado para la resolución de problemas), utilice:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
+
El registro de depuración ayuda al soporte de NetApp a solucionar problemas sin necesidad de cambiar el nivel de registro ni reproducir el problema.



--
====

NOTE: Para obtener opciones de configuración adicionales para el gráfico de Helm, incluidos los ajustes de AutoSupport y el filtrado de espacios de nombres, consulte link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personalizar la instalación de Trident Protect"].
