---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Puede actualizar Trident Protect a la última versión para aprovechar nuevas funciones o correcciones de errores. 
---
= Actualizar Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede actualizar Trident Protect a la última versión para aprovechar nuevas funciones o correcciones de errores.

[NOTE]
====
* Al actualizar desde la versión 24.10, las instantáneas que se ejecutan durante la actualización podrían fallar. Este fallo no impide la creación de instantáneas futuras, ya sean manuales o programadas. Si una instantánea falla durante la actualización, puede crear una nueva manualmente para garantizar la protección de su aplicación.
+
Para evitar posibles fallos, puede desactivar todas las instantáneas programadas antes de la actualización y volver a activarlas después. Sin embargo, esto puede provocar que se pierdan las instantáneas programadas durante el periodo de actualización.

* Para instalaciones en registros privados, asegúrese de que el gráfico Helm y las imágenes necesarias para la versión de destino estén disponibles en su registro privado y verifique que sus valores Helm personalizados sean compatibles con la nueva versión del gráfico. Para obtener más información, consultelink:trident-protect-installation.html["Instalar Trident Protect desde un registro privado"] .


====


== Paso 1: Seleccione una versión

Las versiones de Trident Protect siguen una convención de nomenclatura `YY.MM` basada en fechas, donde "YY" son los dos últimos dígitos del año y "MM" es el mes. Las versiones de punto siguen una `YY.MM.X` convención, donde "X" es el nivel de parche. Vas a seleccionar la versión a la que quieres actualizar según la versión desde la que estás actualizando.

* Puedes hacer una actualización directa a cualquier versión de destino que esté dentro de una ventana de cuatro versiones respecto a la versión que tienes instalada. Por ejemplo, puedes actualizar directamente de 24.10 (o cualquier versión puntual de 24.10) a 25.10.
* Si estás actualizando desde una versión fuera del periodo de cuatro versiones, haz una actualización en varios pasos. Usa las instrucciones de actualización para la link:../earlier-versions.html["versión anterior"] de la que estás actualizando para pasar a la versión más reciente que entre en el periodo de cuatro versiones. Por ejemplo, si estás usando la versión 24.10 y quieres actualizar a la 26.02:
+
.. Primero actualiza de 24.10 a 25.02.
.. Luego actualiza de 25.02 a 26.02.






== Paso 2: actualizar Trident Protect

Para actualizar Trident Protect, realice los siguientes pasos.

.Pasos
. Actualice el repositorio de Trident Helm:
+
[source, console]
----
helm repo update
----
. Actualice los CRD Trident Protect:
+

NOTE: Este paso es necesario si estás actualizando desde una versión anterior a la 25.06, ya que los CRD ahora están incluidos en la tabla de Trident Protect Helm.

+
.. Ejecute este comando para cambiar la administración de CRD de  `trident-protect-crds` a  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Ejecute este comando para eliminar el secreto de Helm para el  `trident-protect-crds` cuadro:
+

NOTE: No desinstale el  `trident-protect-crds` Gráfico usando Helm, ya que esto podría eliminar sus CRD y cualquier dato relacionado.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Mejora Trident Protect:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE: Puede configurar el nivel de registro durante la actualización añadiendo `--set logLevel=debug` al comando de actualización. El nivel de registro predeterminado es `warn` . Se recomienda el registro de depuración para la resolución de problemas, ya que ayuda al soporte de NetApp a diagnosticar problemas sin necesidad de cambios en el nivel de registro ni de reproducir el problema.


