---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Si su entorno cumple los requisitos, puede seguir estos pasos para instalar Trident Protect. 
---
= Instalar y configurar Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si su entorno cumple los requisitos de protección Trident, puede seguir estos pasos para instalar Trident Protect en el clúster. Puede obtener Trident Protect de NetApp o instalarlo desde su propio registro privado. La instalación desde un registro privado es útil si su clúster no puede acceder a Internet.



== Instale Trident Protect

[role="tabbed-block"]
====
.Instale Trident Protect de NetApp
--
.Pasos
. Añada el repositorio Helm de Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Utilice Helm para instalar Trident Protect. Sustituya `<name-of-cluster>` por un nombre de clúster, que se asignará al clúster y se utilizará para identificar los backups y las snapshots del clúster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2506.0 --create-namespace --namespace trident-protect
----


--
.Instale Trident Protect desde un registro privado
--
Puede instalar Trident Protect desde un registro de imágenes privado si su clúster de Kubernetes no puede acceder a Internet. En estos ejemplos, reemplace los valores entre paréntesis por información de su entorno:

.Pasos
. Tire de las siguientes imágenes a su máquina local, actualice las etiquetas y, a continuación, empújelas en su registro privado:
+
[source, console]
----
docker.io/netapp/controller:25.06.0
docker.io/netapp/restic:25.06.0
docker.io/netapp/kopia:25.06.0
docker.io/netapp/kopiablockrestore:25.06.0
docker.io/netapp/trident-autosupport:25.06.0
docker.io/netapp/exechook:25.06.0
docker.io/netapp/resourcebackup:25.06.0
docker.io/netapp/resourcerestore:25.06.0
docker.io/netapp/resourcedelete:25.06.0
docker.io/bitnami/kubectl:1.30.2
gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
----
+
Por ejemplo:

+
[source, console]
----
docker pull docker.io/netapp/controller:25.06.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.06.0 <private-registry-url>/controller:25.06.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.06.0
----
+

NOTE: Para obtener el gráfico de Helm, primero descárguelo en una máquina con acceso a Internet usando `helm pull trident-protect --version 100.2506.0 --repo https://netapp.github.io/trident-protect-helm-chart`, luego copie el resultado `trident-protect-100.2506.0.tgz` transfiera el archivo a su entorno sin conexión e instálelo usando `helm install trident-protect ./trident-protect-100.2506.0.tgz` en lugar de la referencia al repositorio en el paso final.

. Cree el espacio de nombres del sistema Trident Protect:
+
[source, console]
----
kubectl create ns trident-protect
----
. Inicie sesión en el Registro:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Cree un secreto de extracción para utilizarlo en la autenticación del registro privado:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Añada el repositorio Helm de Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Crear un archivo llamado `protectValues.yaml`. Asegúrese de que contiene las siguientes configuraciones de Trident Protect:
+
[source, yaml]
----
---
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
    - name: regcred
webhooksCleanup:
  imagePullSecrets:
    - name: regcred
----
+

NOTE: El `controller.image.registry` Esta configuración se aplica a todas las imágenes de componentes, incluyendo `resourcebackup` y `resourcerestore`. Si envías imágenes a una ruta de repositorio específica dentro de tu registro (por ejemplo, `example.com:443/my-repo`), incluya la ruta completa en el campo del registro. Esto garantizará que todas las imágenes se extraigan de `<private-registry-url>/<image-name>:<tag>`.

. Utilice Helm para instalar Trident Protect. Sustituya `<name_of_cluster>` por un nombre de clúster, que se asignará al clúster y se utilizará para identificar los backups y las snapshots del clúster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2506.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----


--
====

NOTE: Para obtener opciones de configuración adicionales para el gráfico de Helm, incluidos los ajustes de AutoSupport y el filtrado de espacios de nombres, consulte link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personalice la instalación de Trident Protect"].
