---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Personalice la configuración predeterminada de Trident Protect para satisfacer sus necesidades específicas. 
---
= Personalizar la instalación de Trident Protect
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede personalizar la configuración predeterminada de Trident Protect para satisfacer los requisitos específicos de su entorno.



== Especificar los límites de recursos del contenedor Trident Protect

Puede utilizar un archivo de configuración para especificar límites de recursos para los contenedores de Trident Protect después de instalar Trident Protect.  Establecer límites de recursos le permite controlar qué cantidad de recursos del clúster consumen las operaciones de Trident Protect.

.Pasos
. Crear un archivo llamado `resourceLimits.yaml`.
. Complete el archivo con opciones de límite de recursos para los contenedores de Trident Protect según las necesidades de su entorno.
+
El siguiente archivo de configuración de ejemplo muestra la configuración disponible y contiene los valores predeterminados para cada límite de recursos:

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Aplique los valores del `resourceLimits.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Personalizar restricciones de contexto de seguridad

Puede utilizar un archivo de configuración para modificar la restricción de contexto de seguridad (SCC) de OpenShift para los contenedores de Trident Protect después de instalar Trident Protect. Estas restricciones definen las limitaciones de seguridad para los pods en un clúster de Red Hat OpenShift.

.Pasos
. Crear un archivo llamado `sccconfig.yaml`.
. Agregue la opción SCC al archivo y modifique los parámetros según las necesidades de su entorno.
+
El siguiente ejemplo muestra los valores predeterminados de los parámetros para la opción SCC:

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
En esta tabla se describen los parámetros de la opción SCC:

+
|===
| Parámetro | Descripción | Predeterminado 


| cree | Determina si se puede crear un recurso SCC. Un recurso de SCC se creará sólo si `scc.create` se establece en `true` y el proceso de instalación de Helm identifica un entorno de OpenShift. Si no funciona en OpenShift, o si `scc.create` está establecido en `false`, no se creará ningún recurso SCC. | verdadero 


| nombre | Especifica el nombre del SCC. | Trident-protect-job 


| prioridad | Define la prioridad del SCC. Los SCCS con valores de prioridad más altos se evalúan antes que aquellos con valores más bajos. | 1 
|===
. Aplique los valores del `sccconfig.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Esto reemplazará los valores predeterminados por los especificados en el `sccconfig.yaml` archivo.





== Configurar ajustes adicionales del gráfico de timón Trident Protect

Puede personalizar la configuración de AutoSupport y el filtrado de espacios de nombres para satisfacer sus requisitos específicos.  La siguiente tabla describe los parámetros de configuración disponibles:

|===
| Parámetro | Tipo | Descripción 


| autoSupport.proxy | cadena | Configura una URL de proxy para conexiones de NetApp AutoSupport .  Use esto para enrutar las cargas de paquetes de soporte a través de un servidor proxy.  Ejemplo: `http://my.proxy.url` . 


| autoSupport.inseguro | booleano | Omite la verificación TLS para las conexiones proxy de AutoSupport cuando se configura en `true` .  Úselo sólo para conexiones proxy inseguras.  (por defecto: `false` ) 


| autoSupport.enabled | booleano | Habilita o deshabilita las cargas diarias de paquetes de AutoSupport de Trident Protect. Cuando se configura para `false` Las cargas diarias programadas están desactivadas, pero aún puede generar manualmente paquetes de soporte. (por defecto: `true` ) 


| restaurar anotaciones de SkipNamespace | cadena | Lista separada por comas de anotaciones de espacios de nombres para excluir de las operaciones de copia de seguridad y restauración.  Le permite filtrar espacios de nombres según anotaciones. 


| restaurar etiquetas de espacios de nombres de saltos | cadena | Lista separada por comas de etiquetas de espacios de nombres para excluir de las operaciones de copia de seguridad y restauración.  Le permite filtrar espacios de nombres según etiquetas. 
|===
Puede configurar estas opciones mediante un archivo de configuración YAML o indicadores de línea de comandos:

[role="tabbed-block"]
====
.Utilice el archivo YAML
--
.Pasos
. Crea un archivo de configuración y nómbralo `values.yaml` .
. En el archivo que ha creado, agregue las opciones de configuración que desea personalizar.
+
[source, console]
----
autoSupport:
  enabled: false
  proxy: http://my.proxy.url
  insecure: true
restoreSkipNamespaceAnnotations: "annotation1,annotation2"
restoreSkipNamespaceLabels: "label1,label2"
----
. Después de rellenar el `values.yaml` archivo con los valores correctos, aplique el archivo de configuración:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f values.yaml --reuse-values
----


--
.Usar la bandera CLI
--
.Pasos
. Utilice el siguiente comando con el `--set` bandera para especificar parámetros individuales:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set autoSupport.enabled=false \
  --set autoSupport.proxy=http://my.proxy.url \
  --set-string restoreSkipNamespaceAnnotations="{annotation1,annotation2}" \
  --set-string restoreSkipNamespaceLabels="{label1,label2}" \
  --reuse-values
----


--
====


== Restringir los pods de Trident Protect a nodos específicos

Puede utilizar la restricción de selección de nodos nodeSelector de Kubernetes para controlar cuáles de sus nodos son elegibles para ejecutar pods de Trident Protect, según las etiquetas de los nodos.  De forma predeterminada, Trident Protect está restringido a los nodos que ejecutan Linux. Puedes personalizar aún más estas restricciones según tus necesidades.

.Pasos
. Crear un archivo llamado `nodeSelectorConfig.yaml`.
. Agregue la opción nodeSelector al archivo y modifique el archivo para agregar o cambiar etiquetas de nodo para restringir según las necesidades del entorno. Por ejemplo, el siguiente archivo contiene la restricción predeterminada del sistema operativo, pero también se dirige a una región y un nombre de aplicación específicos:
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Aplique los valores del `nodeSelectorConfig.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Esto reemplaza las restricciones predeterminadas por las especificadas en el `nodeSelectorConfig.yaml` archivo.


