---
sidebar: sidebar 
permalink: trident-protect/trident-protect-restore-settings.html 
keywords: trident, protect, restore, data, backup 
summary: Puede personalizar las operaciones de restauración de protección de Trident mediante anotaciones, configuraciones de espacios de nombres y opciones de almacenamiento. 
---
= Utilice la configuración avanzada de restauración de protección de Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede personalizar las operaciones de restauración utilizando configuraciones avanzadas, como anotaciones, configuraciones de espacios de nombres y opciones de almacenamiento para satisfacer sus requisitos específicos.



== Etiquetas y anotaciones del espacio de nombres durante las operaciones de restauración y conmutación al nodo de respaldo

Durante las operaciones de restauración y conmutación al nodo de respaldo, se realizan etiquetas y anotaciones en el espacio de nombres de destino que coincidan con las etiquetas y anotaciones en el espacio de nombres de origen. Se añaden etiquetas o anotaciones del espacio de nombres origen que no existen en el espacio de nombres destino, y las etiquetas o anotaciones que ya existan se sobrescriben para que coincidan con el valor del espacio de nombres origen. Las etiquetas o anotaciones que sólo existen en el espacio de nombres de destino permanecen sin cambios.


NOTE: Si utiliza Red Hat OpenShift, es importante tener en cuenta el papel fundamental que desempeñan las anotaciones de espacios de nombres en los entornos OpenShift.  Las anotaciones de espacio de nombres garantizan que los pods restaurados cumplan con los permisos y las configuraciones de seguridad adecuados definidos por las restricciones de contexto de seguridad (SCC) de OpenShift y puedan acceder a los volúmenes sin problemas de permisos.  Para obtener más información, consulte la https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/authentication_and_authorization/managing-pod-security-policies["Documentación de restricciones de contexto de seguridad de OpenShift"^] .

Puede evitar que se sobrescriban anotaciones específicas en el espacio de nombres de destino mediante el establecimiento de la variable de entorno de Kubernetes `RESTORE_SKIP_NAMESPACE_ANNOTATIONS` antes de llevar a cabo la operación de restauración o conmutación por error. Por ejemplo:

[source, console]
----
kubectl set env -n trident-protect deploy/trident-protect-controller-manager RESTORE_SKIP_NAMESPACE_ANNOTATIONS=<annotation_key_to_skip_1>,<annotation_key_to_skip_2>
----
Si instaló la aplicación de origen con Helm con el `--create-namespace` indicador, se le dará un tratamiento especial a la `name` clave de etiqueta. Durante el proceso de restauración o recuperación tras fallos, Trident protege esta etiqueta al espacio de nombres de destino, pero actualiza el valor al valor del espacio de nombres de destino si el valor del origen coincide con el espacio de nombres de origen. Si este valor no coincide con el espacio de nombres de origen, se copia al espacio de nombres de destino sin cambios.



=== Ejemplo

El siguiente ejemplo presenta un espacio de nombres de origen y destino, cada uno con anotaciones y etiquetas diferentes. Puede ver el estado del espacio de nombres de destino antes y después de la operación, así como cómo las anotaciones y etiquetas se combinan o sobrescriben en el espacio de nombres de destino.



==== Antes de la operación de restauración o conmutación por error

En la siguiente tabla se muestra el estado del ejemplo de espacios de nombres de origen y destino antes de la operación de restauración o conmutación por error:

[cols="1,2a,2a"]
|===
| Espacio de nombres | Anotaciones | Etiquetas 


| Espacio de nombres ns-1 (origen)  a| 
* anotación.uno/clave: “updatedvalue”
* anotación.dos/clave: “verdadero”

 a| 
* entorno=producción
* cumplimiento=hipaa
* name=ns-1




| Espacio de nombres ns-2 (destino)  a| 
* anotación.uno/tecla: “verdadero”
* anotación.tres/clave: “falso”

 a| 
* role=base de datos


|===


==== Después de la operación de restauración

En la siguiente tabla se muestra el estado del espacio de nombres de destino de ejemplo después de la operación de restauración o conmutación por error. Se han agregado algunas claves, algunas se han sobrescrito y la `name` etiqueta se ha actualizado para que coincida con el espacio de nombres de destino:

[cols="1,2a,2a"]
|===
| Espacio de nombres | Anotaciones | Etiquetas 


| Espacio de nombres ns-2 (destino)  a| 
* anotación.uno/clave: “updatedvalue”
* anotación.dos/clave: “verdadero”
* anotación.tres/clave: “falso”

 a| 
* name=ns-2
* cumplimiento=hipaa
* entorno=producción
* role=base de datos


|===


== Campos admitidos

Esta sección describe campos adicionales disponibles para operaciones de restauración.



=== Mapeo de clases de almacenamiento

El `spec.storageClassMapping` El atributo define una asignación de una clase de almacenamiento presente en la aplicación de origen a una nueva clase de almacenamiento en el clúster de destino.  Puede usar esto al migrar aplicaciones entre clústeres con diferentes clases de almacenamiento o al cambiar el backend de almacenamiento para operaciones de BackupRestore.

*Ejemplo:*

[source, yaml]
----
storageClassMapping:
  - destination: "destinationStorageClass1"
    source: "sourceStorageClass1"
  - destination: "destinationStorageClass2"
    source: "sourceStorageClass2"
----


== Anotaciones admitidas

Esta sección enumera las anotaciones compatibles para configurar diversos comportamientos en el sistema. Si el usuario no configura una anotación explícitamente, el sistema utilizará el valor predeterminado.

[cols="1,1,3,1"]
|===
| Anotación | Tipo | Descripción | Valor predeterminado 


| protect.trident.netapp.io/tiempo-de-espera-del-transportador-de-datos-sec | cadena | El tiempo máximo (en segundos) permitido para que la operación de transferencia de datos permanezca detenida. | 300 


| protect.trident.netapp.io/kopia-content-cache-size-limit-mb | entero | El límite de tamaño máximo (en megabytes) para el caché de contenido de Kopia. | 1000 
|===