---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: Comience verificando la preparación de su entorno operativo, clústeres de aplicaciones, aplicaciones y licencias. Asegúrese de que su entorno cumpla los siguientes requisitos para poner en marcha y operar Trident Protect. 
---
= Los requisitos de Trident protegen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comience verificando la preparación de su entorno operativo, clústeres de aplicaciones, aplicaciones y licencias. Asegúrese de que su entorno cumpla los siguientes requisitos para poner en marcha y operar Trident Protect.



== La compatibilidad de clústeres de Kubernetes de Trident protege

Trident Protect es compatible con una amplia gama de ofertas de Kubernetes totalmente gestionadas y autogestionadas, entre las que se incluyen:

* Amazon Elastic Kubernetes Service (EKS)
* Google Kubernetes Engine (GKE)
* Microsoft Azure Kubernetes Service (AKS)
* Red Hat OpenShift
* SUSE Rancher
* Cartera de VMware Tanzania
* Subida de Kubernetes


[NOTE]
====
* Las copias de seguridad de Trident Protect solo se admiten en nodos de cómputo de Linux.  Los nodos de cómputo de Windows no son compatibles con operaciones de copia de seguridad.
* Asegúrese de que el clúster en el que instala Trident Protect está configurado con un controlador de instantáneas en ejecución y los CRD relacionados. Para instalar un controlador de instantánea, consulte https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["estas instrucciones"] .


====


== La compatibilidad del back-end de almacenamiento con Trident protege

Trident Protect es compatible con los siguientes back-ends de almacenamiento:

* Amazon FSX para ONTAP de NetApp
* Cloud Volumes ONTAP
* Cabinas de almacenamiento ONTAP de NetApp
* NetApp Volumes para Google Cloud
* Azure NetApp Files


Asegúrese de que el back-end de almacenamiento cumple los siguientes requisitos:

* Asegúrese de que el almacenamiento de NetApp conectado al clúster utilice Trident 24.02 o más reciente (se recomienda Trident 24.10).


* Asegúrese de tener un back-end de almacenamiento NetApp ONTAP.
* Asegúrese de haber configurado un depósito de almacenamiento de objetos para almacenar backups.
* Cree los espacios de nombres de aplicaciones que desee utilizar para las aplicaciones o las operaciones de gestión de datos de aplicaciones. Trident Protect no crea estos espacios de nombres; si especifica un espacio de nombres no existente en un recurso personalizado, se producirá un error en la operación.




== Requisitos para volúmenes de economía nas

Trident Protect admite las operaciones de backup y restauración en los volúmenes de economía nas. Actualmente no se admiten copias Snapshot, clones y replicación de SnapMirror en volúmenes económicos de nas. Debe habilitar un directorio snapshot para cada volumen económico nas que vaya a utilizar con Trident Protect.

[NOTE]
====
Algunas aplicaciones no son compatibles con volúmenes que usan un directorio Snapshot. Para estas aplicaciones, debe ocultar el directorio Snapshot mediante la ejecución del siguiente comando en el sistema de almacenamiento de ONTAP:

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
Para habilitar el directorio snapshot, ejecute el siguiente comando para cada volumen nas-económico, sustituyéndolo `<volume-UUID>` por el UUID del volumen que desea cambiar:

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Es posible habilitar los directorios de snapshots de forma predeterminada para volúmenes nuevos si se configura la opción Trident backend configuration `snapshotDir` en `true`. Los volúmenes existentes no se ven afectados.



== Protección de datos con máquinas virtuales de KubeVirt

Trident Protect proporciona capacidades de congelación y descongelación del sistema de archivos para las máquinas virtuales KubeVirt durante las operaciones de protección de datos para garantizar la coherencia de los datos.  El método de configuración y el comportamiento predeterminado para las operaciones de congelación de máquinas virtuales varían entre las versiones de Trident Protect; las versiones más recientes ofrecen una configuración simplificada mediante parámetros del gráfico Helm.


NOTE: Durante las operaciones de restauración, cualquier  `VirtualMachineSnapshots` Los datos creados para una máquina virtual (VM) no se restauran.

.Trident Protect 25.10 y versiones posteriores
[%collapsible%open]
====
Trident Protect congela y descongela automáticamente los sistemas de archivos de KubeVirt durante las operaciones de protección de datos para garantizar la coherencia.  A partir de Trident Protect 25.10, puede deshabilitar este comportamiento mediante la opción `vm.freeze` parámetro durante la instalación del gráfico Helm.  El parámetro está habilitado por defecto.

[source, console]
----
helm install ... --set vm.freeze=false ...
----
====
.Trident protege del 24.10.1 al 25.06
[%collapsible]
====
A partir de Trident Protect 24.10.1, Trident Protect congela y descongela automáticamente los sistemas de archivos KubeVirt durante las operaciones de protección de datos. De manera opcional, puede deshabilitar este comportamiento automático mediante el siguiente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----
====
.Trident Protect 24,10
[%collapsible]
====
Trident Protect 24,10 no garantiza automáticamente un estado coherente para los sistemas de archivos de máquinas virtuales KubeVirt durante las operaciones de protección de datos. Si desea proteger los datos de las máquinas virtuales KubeVirt con Trident Protect 24,10, debe habilitar manualmente la funcionalidad de congelación/descongelación para los sistemas de archivos antes de la operación de protección de datos. Esto garantiza que los sistemas de archivos estén en un estado consistente.

Puede configurar Trident Protect 24,10 para gestionar la congelación y descongelación del sistema de archivos de la máquina virtual durante las operaciones de protección de datos, mediante link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["configurar la virtualización"^]el siguiente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
====


== Requisitos para la replicación de SnapMirror

La replicación de NetApp SnapMirror está disponible para usar con Trident Protect para las siguientes soluciones de ONTAP:

* Clústeres de NetApp FAS, AFF y ASA en las instalaciones
* ONTAP Select de NetApp
* Cloud Volumes ONTAP de NetApp
* Amazon FSX para ONTAP de NetApp




=== Requisitos de clústeres de ONTAP para la replicación de SnapMirror

Asegúrese de que el clúster de ONTAP cumple los siguientes requisitos si tiene pensado utilizar la replicación de SnapMirror:

* *NetApp Trident*: NetApp Trident debe existir en los clústeres de Kubernetes de origen y destino que utilizan ONTAP como back-end. Trident Protect admite la replicación con tecnología de NetApp SnapMirror mediante clases de almacenamiento respaldadas por los controladores siguientes:
+
** `ontap-nas` : NFS
** `ontap-san` : iSCSI
** `ontap-san` :FC
** `ontap-san` :NVMe/TCP (requiere la versión mínima de ONTAP 9.15.1)


* *Licencias*: Las licencias asíncronas de SnapMirror de ONTAP que utilizan el paquete de protección de datos deben estar habilitadas en los clústeres de ONTAP de origen y de destino. Consulte https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Información general sobre las licencias de SnapMirror en ONTAP"^] si desea obtener más información.
+
A partir de ONTAP 9.10.1, todas las licencias se proporcionan como archivo de licencia de NetApp (NLF), que es un solo archivo que admite varias funciones. Consulte link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licencias incluidas con ONTAP One"^] si desea obtener más información.

+

NOTE: Sólo se admite la protección asincrónica SnapMirror.





=== Consideraciones sobre la relación de paridad para la replicación de SnapMirror

Compruebe que el entorno cumple los siguientes requisitos si piensa utilizar la paridad de back-end de almacenamiento:

* *Cluster y SVM*: Los back-ends de almacenamiento ONTAP deben ser peered. Consulte https://docs.netapp.com/us-en/ontap/peering/index.html["Información general sobre relaciones entre iguales de clústeres y SVM"^] si desea obtener más información.
+

NOTE: Compruebe que los nombres de las SVM utilizados en la relación de replicación entre dos clústeres de ONTAP sean únicos.

* *NetApp Trident y SVM*: las SVM remotas emparejadas deben estar disponibles para NetApp Trident en el clúster de destino.
* *Backends administrados*: Necesitas agregar y administrar backends de almacenamiento ONTAP en Trident Protect para crear una relación de replicación.




=== Configuración de Trident/ONTAP para la replicación de SnapMirror

Trident Protect requiere que configure al menos un back-end de almacenamiento que admita la replicación para los clústeres de origen y destino. Si los clústeres de origen y destino son los mismos, la aplicación de destino debe usar un back-end de almacenamiento diferente al de la aplicación de origen para obtener la mejor resiliencia.



=== Requisitos del clúster de Kubernetes para la replicación de SnapMirror

Asegúrese de que sus clústeres de Kubernetes cumplan con los siguientes requisitos:

* *Accesibilidad de AppVault*: tanto los clústeres de origen como de destino deben tener acceso a la red para leer y escribir en AppVault para la replicación de objetos de la aplicación.
* *Conectividad de red*: configure reglas de firewall, permisos de bucket y listas de IP permitidas para habilitar la comunicación entre ambos clústeres y AppVault a través de WAN.



NOTE: Muchos entornos empresariales implementan políticas de firewall estrictas en las conexiones WAN.  Verifique estos requisitos de red con su equipo de infraestructura antes de configurar la replicación.
