---
sidebar: sidebar 
permalink: trident-protect/trident-protect-protect-apps.html 
keywords: protect, snapshots, demand, configuration, cluster, appvault 
summary: Proteger todas las aplicaciones mediante la toma de snapshots y backups a travĂ©s de una polĂ­tica de protecciĂ³n automatizada o de manera ad hoc. 
---
= Proteja las aplicaciones con Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede proteger todas las aplicaciones administradas por Trident Protect tomando instantĂ¡neas y copias de seguridad mediante una polĂ­tica de protecciĂ³n automatizada o de forma ad hoc.


NOTE: Puede configurar Trident Protect para congelar y descongelar sistemas de archivos durante operaciones de protecciĂ³n de datos. link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Obtenga mĂ¡s informaciĂ³n sobre cĂ³mo configurar la congelaciĂ³n del sistema de archivos con Trident Protect"].



== Crear una snapshot bajo demanda

Puede crear una snapshot bajo demanda en cualquier momento.


NOTE: Los recursos de Ă¡mbito de clĂºster se incluyen en un backup, una copia de Snapshot o un clon si se hace referencia explĂ­citamente a estos en la definiciĂ³n de la aplicaciĂ³n o si tienen referencias a cualquiera de los espacios de nombres de la aplicaciĂ³n.

[role="tabbed-block"]
====
.Cree una instantĂ¡nea con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asĂ­gnele un nombre `trident-protect-snapshot-cr.yaml`.
. En el archivo creado, configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre Ăºnico y sensible para su entorno.
** *Spec.applicationRef*: El nombre de Kubernetes de la aplicaciĂ³n a la instantĂ¡nea.
** *Spec.appVaultRef*: (_required_) El nombre del AppVault donde se debe almacenar el contenido de la instantĂ¡nea (metadatos).
** *Spec.reclaimer Policy*: (_Optional_) define lo que sucede con el AppArchive de una instantĂ¡nea cuando se elimina el CR de la instantĂ¡nea. Esto significa que incluso cuando se define en `Retain`, la instantĂ¡nea se suprimirĂ¡. Opciones vĂ¡lidas:
+
*** `Retain` (predeterminado)
*** `Delete`
+
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Snapshot
metadata:
  namespace: my-app-namespace
  name: my-cr-name
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  reclaimPolicy: Delete
----




. DespuĂ©s de rellenar `trident-protect-snapshot-cr.yaml` el archivo con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f trident-protect-snapshot-cr.yaml
----


--
.Cree una copia Snapshot mediante la CLI
--
.Pasos
. Cree la instantĂ¡nea, reemplazando valores entre parĂ©ntesis con informaciĂ³n de su entorno. Por ejemplo:
+
[source, console]
----
tridentctl-protect create snapshot <my_snapshot_name> --appvault <my_appvault_name> --app <name_of_app_to_snapshot> -n <application_namespace>
----


--
====


== Cree un backup bajo demanda

Puede realizar una copia de seguridad de una aplicaciĂ³n en cualquier momento.


NOTE: Los recursos de Ă¡mbito de clĂºster se incluyen en un backup, una copia de Snapshot o un clon si se hace referencia explĂ­citamente a estos en la definiciĂ³n de la aplicaciĂ³n o si tienen referencias a cualquiera de los espacios de nombres de la aplicaciĂ³n.

.Antes de empezar
AsegĂºrese de que la caducidad del token de sesiĂ³n de AWS sea suficiente para cualquier operaciĂ³n de copia de seguridad de S3 que se ejecute durante mucho tiempo. Si el token caduca durante la operaciĂ³n de copia de seguridad, la operaciĂ³n puede fallar.

* Consulte el https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html["DocumentaciĂ³n de la API de AWS"^] para obtener mĂ¡s informaciĂ³n sobre la comprobaciĂ³n de la caducidad del token de sesiĂ³n actual.
* Consulte el documento para https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html["DocumentaciĂ³n de AWS IAM"^] obtener mĂ¡s informaciĂ³n acerca de las credenciales con recursos de AWS.


[role="tabbed-block"]
====
.Cree una copia de seguridad con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asĂ­gnele un nombre `trident-protect-backup-cr.yaml`.
. En el archivo creado, configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre Ăºnico y sensible para su entorno.
** *Spec.applicationRef*: (_required_) El nombre de Kubernetes de la aplicaciĂ³n para realizar una copia de seguridad.
** *Spec.appVaultRef*: (_required_) El nombre del AppVault donde se debe almacenar el contenido de la copia de seguridad.
** *SPEC.DATAMOVER*: (_Optional_) Una cadena que indica quĂ© herramienta de copia de seguridad usar para la operaciĂ³n de copia de seguridad. Valores posibles (distingue mayĂºsculas de minĂºsculas):
+
*** `Restic`
*** `Kopia` (predeterminado)


** *Spec.reclaimer Policy*: (_Optional_) define lo que sucede con una copia de seguridad cuando se libera de su reclamaciĂ³n. Los posibles valores son los siguientes:
+
*** `Delete`
*** `Retain` (predeterminado)


** *spec.snapshotRef*: (_Opcional_): Nombre de la instantĂ¡nea que se utilizarĂ¡ como origen de la copia de seguridad. Si no se proporciona, se crearĂ¡ una instantĂ¡nea temporal y se realizarĂ¡ una copia de seguridad.
+
Ejemplo YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Backup
metadata:
  namespace: my-app-namespace
  name: my-cr-name
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  dataMover: Kopia
----


. DespuĂ©s de rellenar `trident-protect-backup-cr.yaml` el archivo con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f trident-protect-backup-cr.yaml
----


--
.Cree un backup con la interfaz de lĂ­nea de comandos
--
.Pasos
. Cree el backup sustituyendo valores entre parĂ©ntesis con informaciĂ³n de su entorno. Por ejemplo:
+
[source, console]
----
tridentctl-protect create backup <my_backup_name> --appvault <my-vault-name> --app <name_of_app_to_back_up> --data-mover <Kopia_or_Restic> -n <application_namespace>
----
+
Opcionalmente, puede utilizar `--full-backup` el indicador para especificar si una copia de seguridad debe ser no incremental. Por defecto, todos los backups son incrementales. Cuando se utiliza este indicador, la copia de seguridad pasa a ser no incremental. Es mejor realizar backups completos de forma periĂ³dica y despuĂ©s realizar backups incrementales entre backups completos para minimizar el riesgo asociado a las restauraciones.



--
====


=== Anotaciones de respaldo admitidas

La siguiente tabla describe las anotaciones que puede utilizar al crear una copia de seguridad de CR:

[cols="2,1,3,1"]
|===
| AnotaciĂ³n | Tipo | DescripciĂ³n | Valor predeterminado 


| proteger.trident.netapp.io/copia-de-seguridad-completa | cadena | Especifica si una copia de seguridad debe ser no incremental. Empezar a `true` para crear una copia de seguridad no incremental. La mejor prĂ¡ctica es realizar una copia de seguridad completa periĂ³dicamente y luego realizar copias de seguridad incrementales entre las copias de seguridad completas para minimizar el riesgo asociado con las restauraciones. | "falso" 


| protect.trident.netapp.io/snapshot-complete-timeout | cadena | Tiempo mĂ¡ximo permitido para que se complete la operaciĂ³n de instantĂ¡nea general. | "60 m" 


| protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout | cadena | Tiempo mĂ¡ximo permitido para que las instantĂ¡neas de volumen alcancen el estado listo para usar. | "30 m" 


| protect.trident.netapp.io/volume-snapshots-created-timeout | cadena | Tiempo mĂ¡ximo permitido para la creaciĂ³n de instantĂ¡neas de volumen. | "5 m" 


| protect.trident.netapp.io/pvc-bind-timeout-sec | cadena | Tiempo mĂ¡ximo (en segundos) que se debe esperar para que cualquier PersistentVolumeClaim (PVC) reciĂ©n creado llegue al `Bound` fase antes de que fallen las operaciones. | "1200" (20 minutos) 
|===


== Cree un programa de protecciĂ³n de datos

Una polĂ­tica de protecciĂ³n protege una aplicaciĂ³n mediante la creaciĂ³n de instantĂ¡neas, copias de seguridad o ambas segĂºn un cronograma definido.  Puede elegir crear instantĂ¡neas y copias de seguridad cada hora, dĂ­a, semana o mes, y puede especificar la cantidad de copias que desea conservar.  Puede programar una copia de seguridad completa no incremental mediante la anotaciĂ³n full-backup-rule.  De forma predeterminada, todas las copias de seguridad son incrementales.  Realizar una copia de seguridad completa periĂ³dicamente, junto con copias de seguridad incrementales entre ellas, ayuda a reducir el riesgo asociado con las restauraciones.

[NOTE]
====
* Puede crear programaciones para instantĂ¡neas Ăºnicamente configurando `backupRetention` a cero y `snapshotRetention` a un valor mayor que cero.  ConfiguraciĂ³n `snapshotRetention` Poner a cero significa que cualquier copia de seguridad programada seguirĂ¡ creando instantĂ¡neas, pero Ă©stas serĂ¡n temporales y se eliminarĂ¡n inmediatamente despuĂ©s de que se complete la copia de seguridad.
* Los recursos de Ă¡mbito de clĂºster se incluyen en un backup, una copia de Snapshot o un clon si se hace referencia explĂ­citamente a estos en la definiciĂ³n de la aplicaciĂ³n o si tienen referencias a cualquiera de los espacios de nombres de la aplicaciĂ³n.


====
[role="tabbed-block"]
====
.Crear un horario mediante un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asĂ­gnele un nombre `trident-protect-schedule-cr.yaml`.
. En el archivo creado, configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre Ăºnico y sensible para su entorno.
** *SPEC.DATAMOVER*: (_Optional_) Una cadena que indica quĂ© herramienta de copia de seguridad usar para la operaciĂ³n de copia de seguridad. Valores posibles (distingue mayĂºsculas de minĂºsculas):
+
*** `Restic`
*** `Kopia` (predeterminado)


** *Spec.applicationRef*: El nombre de Kubernetes de la aplicaciĂ³n para realizar una copia de seguridad.
** *Spec.appVaultRef*: (_required_) El nombre del AppVault donde se debe almacenar el contenido de la copia de seguridad.
** *spec.backupRetention*: (_Obligatorio_) La cantidad de copias de seguridad a conservar. Cero indica que no se deben crear copias de seguridad (solo instantĂ¡neas).
** *spec.backupReclaimPolicy*: (_Opcional_) Determina quĂ© sucede con una copia de seguridad si el CR de la copia de seguridad se elimina durante su perĂ­odo de retenciĂ³n.  DespuĂ©s del perĂ­odo de retenciĂ³n, las copias de seguridad siempre se eliminan. Valores posibles (distingue entre mayĂºsculas y minĂºsculas):
+
*** `Retain` (predeterminado)
*** `Delete`


** *spec.snapshotRetention*: (_Obligatorio_) La cantidad de instantĂ¡neas a conservar. El valor cero indica que no se deben crear instantĂ¡neas.
** *spec.snapshotReclaimPolicy*: (_Opcional_) Determina quĂ© sucede con una instantĂ¡nea si el CR de la instantĂ¡nea se elimina durante su perĂ­odo de retenciĂ³n.  DespuĂ©s del perĂ­odo de retenciĂ³n, las instantĂ¡neas siempre se eliminan. Valores posibles (distingue entre mayĂºsculas y minĂºsculas):
+
*** `Retain`
*** `Delete`(por defecto)


** *spec.granularity*: La frecuencia con la que debe ejecutarse el horario. Los posibles valores, junto con los campos asociados necesarios:
+
*** `Hourly`(requiere que usted especifique `spec.minute` )
*** `Daily`(requiere que usted especifique `spec.minute` y `spec.hour` )
*** `Weekly`(requiere que usted especifique `spec.minute, spec.hour` , y `spec.dayOfWeek` )
*** `Monthly`(requiere que usted especifique `spec.minute, spec.hour` , y `spec.dayOfMonth` )
*** `Custom`


** *spec.dayOfMonth*: (_Opcional_) El dĂ­a del mes (1 - 31) en que debe ejecutarse la programaciĂ³n.  Este campo es obligatorio si la granularidad estĂ¡ establecida en `Monthly` .  El valor debe proporcionarse como una cadena.
** *spec.dayOfWeek*: (_Opcional_) El dĂ­a de la semana (0 - 7) en que debe ejecutarse la programaciĂ³n.  Los valores de 0 o 7 indican domingo.  Este campo es obligatorio si la granularidad estĂ¡ establecida en `Weekly` .  El valor debe proporcionarse como una cadena.
** *spec.hour*: (_Opcional_) La hora del dĂ­a (0 - 23) en que debe ejecutarse el programa.  Este campo es obligatorio si la granularidad estĂ¡ establecida en `Daily` , `Weekly` , o `Monthly` .  El valor debe proporcionarse como una cadena.
** *spec.minute*: (_Opcional_) El minuto de la hora (0 - 59) en que debe ejecutarse el programa.  Este campo es obligatorio si la granularidad estĂ¡ establecida en `Hourly` , `Daily` , `Weekly` , o `Monthly` .  El valor debe proporcionarse como una cadena.
** *spec.runImmediately*: (_Opcional_) Establece en `true` para activar una ejecuciĂ³n de lĂ­nea de base Ăºnica e inmediata (copia de seguridad y/o instantĂ¡nea segĂºn la configuraciĂ³n de retenciĂ³n) cuando se crea el programa. Por defecto es `false`. Esto no modifica la recurrencia posterior.
+
Ejemplo de YAML para programaciĂ³n de copias de seguridad y instantĂ¡neas:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  namespace: my-app-namespace
  name: my-cr-name
spec:
  dataMover: Kopia
  applicationRef: my-application
  appVaultRef: appvault-name
  backupRetention: "15"
  snapshotRetention: "15"
  granularity: Daily
  hour: "0"
  minute: "0"
----
+
Ejemplo de YAML para una programaciĂ³n de solo instantĂ¡neas:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  namespace: my-app-namespace
  name: my-snapshot-schedule
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  backupRetention: "0"
  snapshotRetention: "15"
  granularity: Daily
  hour: "2"
  minute: "0"
----
+
Ejemplo YAML para programaciĂ³n con ejecuciĂ³n inmediata:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  namespace: my-app-namespace
  name: my-daily-schedule-run-immediately
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  backupRetention: "7"
  snapshotRetention: "7"
  granularity: Daily
  hour: "3"
  minute: "0"
  runImmediately: true
----


. DespuĂ©s de rellenar `trident-protect-schedule-cr.yaml` el archivo con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f trident-protect-schedule-cr.yaml
----


--
.Cree una programaciĂ³n con la CLI
--
.Pasos
. Cree el programa de protecciĂ³n, reemplazando los valores entre parĂ©ntesis con informaciĂ³n de su entorno. Por ejemplo:
+

NOTE: Puede usar `tridentctl-protect create schedule --help` para ver informaciĂ³n de ayuda detallada de este comando.

+
[source, console]
----
tridentctl-protect create schedule <my_schedule_name> \
  --appvault <my_appvault_name> \
  --app <name_of_app_to_snapshot> \
  --backup-retention <how_many_backups_to_retain> \
  --backup-reclaim-policy <Retain|Delete (default Retain)> \
  --data-mover <Kopia_or_Restic> \
  --day-of-month <day_of_month_to_run_schedule> \
  --day-of-week <day_of_week_to_run_schedule> \
  --granularity <frequency_to_run> \
  --hour <hour_of_day_to_run> \
  --minute <minute_of_hour_to_run> \
  --recurrence-rule <recurrence> \
  --snapshot-retention <how_many_snapshots_to_retain> \
  --snapshot-reclaim-policy <Retain|Delete (default Delete)> \
  --full-backup-rule <string> \
  --run-immediately <true|false> \
  -n <application_namespace>
----
+
Las siguientes banderas proporcionan control adicional sobre su programaciĂ³n:

+
** *ProgramaciĂ³n de copia de seguridad completa*: utilice la `--full-backup-rule` bandera para programar copias de seguridad completas no incrementales. Esta bandera sĂ³lo funciona con `--granularity Daily`. Valores posibles:
+
*** `Always`:Cree una copia de seguridad completa todos los dĂ­as.
*** DĂ­as de la semana especĂ­ficos: especifique uno o mĂ¡s dĂ­as separados por comas (por ejemplo, `"Monday,Thursday"`). Valores vĂ¡lidos: lunes, martes, miĂ©rcoles, jueves, viernes, sĂ¡bado, domingo.
+

NOTE: El `--full-backup-rule` La bandera no funciona con granularidad horaria, semanal o mensual.



** *ProtecciĂ³n inicial inmediata*: Usa `--run-immediately true` para crear una copia de seguridad o instantĂ¡nea inicial inmediatamente cuando se crea la programaciĂ³n, en lugar de esperar a la primera hora de ejecuciĂ³n programada. El valor predeterminado es `false`.
** *Horarios solo de instantĂ¡neas*: Establecer `--backup-retention 0` y especifique un valor mayor que cero para `--snapshot-retention`.




--
====


=== Anotaciones de programaciĂ³n admitidas

La siguiente tabla describe las anotaciones que puede utilizar al crear una solicitud de cambio de programaciĂ³n:

[cols="2,1,3,1"]
|===
| AnotaciĂ³n | Tipo | DescripciĂ³n | Valor predeterminado 


| proteger.trident.netapp.io/regla-de-copia-de-seguridad-completa | cadena | Especifica la regla para programar copias de seguridad completas. Puedes configurarlo para `Always` para realizar copias de seguridad completas y constantes o personalizarlas segĂºn sus necesidades. Por ejemplo, si elige granularidad diaria, puede especificar los dĂ­as de la semana en los que debe realizarse la copia de seguridad completa (por ejemplo, `"Monday,Thursday"`). Los valores vĂ¡lidos para dĂ­as de la semana son: lunes, martes, miĂ©rcoles, jueves, viernes, sĂ¡bado y domingo. Tenga en cuenta que esta anotaciĂ³n solo se puede utilizar con programaciones que tengan `granularity` empezar a `Daily`. | No configurado (todas las copias de seguridad son incrementales) 


| protect.trident.netapp.io/snapshot-complete-timeout | cadena | Tiempo mĂ¡ximo permitido para que se complete la operaciĂ³n de instantĂ¡nea general. | "60 m" 


| protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout | cadena | Tiempo mĂ¡ximo permitido para que las instantĂ¡neas de volumen alcancen el estado listo para usar. | "30 m" 


| protect.trident.netapp.io/volume-snapshots-created-timeout | cadena | Tiempo mĂ¡ximo permitido para la creaciĂ³n de instantĂ¡neas de volumen. | "5 m" 


| protect.trident.netapp.io/pvc-bind-timeout-sec | cadena | Tiempo mĂ¡ximo (en segundos) que se debe esperar para que cualquier PersistentVolumeClaim (PVC) reciĂ©n creado llegue al `Bound` fase antes de que fallen las operaciones. | "1200" (20 minutos) 
|===


== Eliminar una copia de Snapshot

Elimine las snapshots programadas o bajo demanda que ya no necesite.

.Pasos
. Elimine el CR de instantĂ¡nea asociado a la instantĂ¡nea:
+
[source, console]
----
kubectl delete snapshot <snapshot_name> -n my-app-namespace
----




== Eliminar una copia de seguridad

Elimine los backups programados o bajo demanda que ya no necesita.


NOTE: AsegĂºrese de que la polĂ­tica de recuperaciĂ³n estĂ© configurada en  `Delete` Para eliminar todos los datos de respaldo del almacenamiento de objetos. La configuraciĂ³n predeterminada de la polĂ­tica es  `Retain` Para evitar la pĂ©rdida accidental de datos. Si la polĂ­tica no se modifica a  `Delete` Los datos de respaldo permanecerĂ¡n en el almacenamiento de objetos y serĂ¡ necesario eliminarlos manualmente.

.Pasos
. Elimine el CR de backup asociado con el backup:
+
[source, console]
----
kubectl delete backup <backup_name> -n my-app-namespace
----




== Compruebe el estado de una operaciĂ³n de backup

Puede usar la lĂ­nea de comandos para comprobar el estado de una operaciĂ³n de backup que estĂ¡ en curso, se completa o tiene errores.

.Pasos
. Utilice el siguiente comando para recuperar el estado de la operaciĂ³n de copia de seguridad, sustituyendo los valores entre corchetes por informaciĂ³n de su entorno:
+
[source, console]
----
kubectl get backup -n <namespace_name> <my_backup_cr_name> -o jsonpath='{.status}'
----




== Permita el backup y la restauraciĂ³n para las operaciones de azure-NetApp-files (ANF)

Si ha instalado Trident Protect, puede habilitar la funcionalidad de copia de seguridad y restauraciĂ³n que ahorra espacio para los backends de almacenamiento que usan la clase de almacenamiento azure-netapp-files y se crearon antes de Trident 24.06. Esta funcionalidad funciona con volĂºmenes NFSv4 y no consume espacio adicional del grupo de capacidad.

.Antes de empezar
AsegĂºrese de lo siguiente:

* Ha instalado Trident Protect.
* Ha definido una aplicaciĂ³n en Trident Protect. Esta aplicaciĂ³n tendrĂ¡ una funcionalidad de protecciĂ³n limitada hasta que complete este procedimiento.
*  `azure-netapp-files`SeleccionĂ³ como clase de almacenamiento predeterminada para el back-end de almacenamiento.


.Expanda para obtener pasos de configuraciĂ³n
[%collapsible]
====
. Haga lo siguiente en Trident si el volumen ANF se creĂ³ antes de actualizar a Trident 24,10:
+
.. Habilite el directorio de instantĂ¡neas para cada VP basado en azure-NetApp-files y asociado con la aplicaciĂ³n:
+
[source, console]
----
tridentctl update volume <pv name> --snapshot-dir=true -n trident
----
.. Confirme que el directorio de snapshots se haya habilitado para cada VP asociado:
+
[source, console]
----
tridentctl get volume <pv name> -n trident -o yaml | grep snapshotDir
----
+
Respuesta:

+
[listing]
----
snapshotDirectory: "true"
----
+
Cuando el directorio de instantĂ¡neas no estĂ¡ habilitado, Trident Protect elige la funcionalidad de copia de seguridad regular, que consume temporalmente espacio en el grupo de capacidad durante el proceso de copia de seguridad. En este caso, asegĂºrese de que haya suficiente espacio disponible en el grupo de capacidad para crear un volumen temporal del tamaĂ±o del volumen del que se estĂ¡ realizando la copia de seguridad.





.Resultado
La aplicaciĂ³n estĂ¡ lista para realizar copias de seguridad y restaurar mediante Trident Protect. Cada PVC tambiĂ©n estĂ¡ disponible para ser utilizado por otras aplicaciones para copias de seguridad y restauraciones.

====