---
sidebar: sidebar 
permalink: trident-protect/trident-protect-protect-apps.html 
keywords: protect, snapshots, demand, configuration, cluster, appvault 
summary: Proteger todas las aplicaciones mediante la toma de snapshots y backups a través de una política de protección automatizada o de manera ad hoc. 
---
= Proteja las aplicaciones con Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede proteger todas las aplicaciones administradas por Trident Protect tomando instantáneas y copias de seguridad mediante una política de protección automatizada o de forma ad hoc.


NOTE: Puede configurar Trident Protect para congelar y descongelar sistemas de archivos durante operaciones de protección de datos. link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Obtenga más información sobre cómo configurar la congelación del sistema de archivos con Trident Protect"].



== Crear una snapshot bajo demanda

Puede crear una snapshot bajo demanda en cualquier momento.


NOTE: Los recursos de ámbito de clúster se incluyen en un backup, una copia de Snapshot o un clon si se hace referencia explícitamente a estos en la definición de la aplicación o si tienen referencias a cualquiera de los espacios de nombres de la aplicación.

[role="tabbed-block"]
====
.Cree una instantánea con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `trident-protect-snapshot-cr.yaml`.
. En el archivo creado, configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre único y sensible para su entorno.
** *Spec.applicationRef*: El nombre de Kubernetes de la aplicación a la instantánea.
** *Spec.appVaultRef*: (_required_) El nombre del AppVault donde se debe almacenar el contenido de la instantánea (metadatos).
** *Spec.reclaimer Policy*: (_Optional_) define lo que sucede con el AppArchive de una instantánea cuando se elimina el CR de la instantánea. Esto significa que incluso cuando se define en `Retain`, la instantánea se suprimirá. Opciones válidas:
+
*** `Retain` (predeterminado)
*** `Delete`
+
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Snapshot
metadata:
  namespace: my-app-namespace
  name: my-cr-name
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  reclaimPolicy: Delete
----




. Después de rellenar `trident-protect-snapshot-cr.yaml` el archivo con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f trident-protect-snapshot-cr.yaml
----


--
.Cree una copia Snapshot mediante la CLI
--
.Pasos
. Cree la instantánea, reemplazando valores entre paréntesis con información de su entorno. Por ejemplo:
+
[source, console]
----
tridentctl-protect create snapshot <my_snapshot_name> --appvault <my_appvault_name> --app <name_of_app_to_snapshot> -n <application_namespace>
----


--
====


== Cree un backup bajo demanda

Puede realizar una copia de seguridad de una aplicación en cualquier momento.


NOTE: Los recursos de ámbito de clúster se incluyen en un backup, una copia de Snapshot o un clon si se hace referencia explícitamente a estos en la definición de la aplicación o si tienen referencias a cualquiera de los espacios de nombres de la aplicación.

.Antes de empezar
Asegúrese de que la caducidad del token de sesión de AWS sea suficiente para cualquier operación de copia de seguridad de S3 que se ejecute durante mucho tiempo. Si el token caduca durante la operación de copia de seguridad, la operación puede fallar.

* Consulte el https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html["Documentación de la API de AWS"^] para obtener más información sobre la comprobación de la caducidad del token de sesión actual.
* Consulte el documento para https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html["Documentación de AWS IAM"^] obtener más información acerca de las credenciales con recursos de AWS.


[role="tabbed-block"]
====
.Cree una copia de seguridad con un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `trident-protect-backup-cr.yaml`.
. En el archivo creado, configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre único y sensible para su entorno.
** *Spec.applicationRef*: (_required_) El nombre de Kubernetes de la aplicación para realizar una copia de seguridad.
** *Spec.appVaultRef*: (_required_) El nombre del AppVault donde se debe almacenar el contenido de la copia de seguridad.
** *SPEC.DATAMOVER*: (_Optional_) Una cadena que indica qué herramienta de copia de seguridad usar para la operación de copia de seguridad. Valores posibles (distingue mayúsculas de minúsculas):
+
*** `Restic`
*** `Kopia` (predeterminado)


** *Spec.reclaimer Policy*: (_Optional_) define lo que sucede con una copia de seguridad cuando se libera de su reclamación. Los posibles valores son los siguientes:
+
*** `Delete`
*** `Retain` (predeterminado)


** *spec.snapshotRef*: (_Opcional_): Nombre de la instantánea que se utilizará como origen de la copia de seguridad. Si no se proporciona, se creará una instantánea temporal y se realizará una copia de seguridad.
+
Ejemplo YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Backup
metadata:
  namespace: my-app-namespace
  name: my-cr-name
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  dataMover: Kopia
----


. Después de rellenar `trident-protect-backup-cr.yaml` el archivo con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f trident-protect-backup-cr.yaml
----


--
.Cree un backup con la interfaz de línea de comandos
--
.Pasos
. Cree el backup sustituyendo valores entre paréntesis con información de su entorno. Por ejemplo:
+
[source, console]
----
tridentctl-protect create backup <my_backup_name> --appvault <my-vault-name> --app <name_of_app_to_back_up> --data-mover <Kopia_or_Restic> -n <application_namespace>
----
+
Opcionalmente, puede utilizar `--full-backup` el indicador para especificar si una copia de seguridad debe ser no incremental. Por defecto, todos los backups son incrementales. Cuando se utiliza este indicador, la copia de seguridad pasa a ser no incremental. Es mejor realizar backups completos de forma periódica y después realizar backups incrementales entre backups completos para minimizar el riesgo asociado a las restauraciones.



--
====


=== Anotaciones de respaldo admitidas

La siguiente tabla describe las anotaciones que puede utilizar al crear una copia de seguridad de CR:

[cols="2,1,3,1"]
|===
| Anotación | Tipo | Descripción | Valor predeterminado 


| proteger.trident.netapp.io/copia-de-seguridad-completa | cadena | Especifica si una copia de seguridad debe ser no incremental. Empezar a `true` para crear una copia de seguridad no incremental. La mejor práctica es realizar una copia de seguridad completa periódicamente y luego realizar copias de seguridad incrementales entre las copias de seguridad completas para minimizar el riesgo asociado con las restauraciones. | "falso" 


| protect.trident.netapp.io/snapshot-complete-timeout | cadena | Tiempo máximo permitido para que se complete la operación de instantánea general. | "60 m" 


| protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout | cadena | Tiempo máximo permitido para que las instantáneas de volumen alcancen el estado listo para usar. | "30 m" 


| protect.trident.netapp.io/volume-snapshots-created-timeout | cadena | Tiempo máximo permitido para la creación de instantáneas de volumen. | "5 m" 


| protect.trident.netapp.io/pvc-bind-timeout-sec | cadena | Tiempo máximo (en segundos) que se debe esperar para que cualquier PersistentVolumeClaim (PVC) recién creado llegue al `Bound` fase antes de que fallen las operaciones. | "1200" (20 minutos) 
|===


== Cree un programa de protección de datos

Una política de protección protege una aplicación mediante la creación de instantáneas, copias de seguridad o ambas según un cronograma definido.  Puede elegir crear instantáneas y copias de seguridad cada hora, día, semana o mes, y puede especificar la cantidad de copias que desea conservar.  Puede programar una copia de seguridad completa no incremental mediante la anotación full-backup-rule.  De forma predeterminada, todas las copias de seguridad son incrementales.  Realizar una copia de seguridad completa periódicamente, junto con copias de seguridad incrementales entre ellas, ayuda a reducir el riesgo asociado con las restauraciones.

[NOTE]
====
* Puede crear programaciones para instantáneas únicamente configurando `backupRetention` a cero y `snapshotRetention` a un valor mayor que cero.  Configuración `snapshotRetention` Poner a cero significa que cualquier copia de seguridad programada seguirá creando instantáneas, pero éstas serán temporales y se eliminarán inmediatamente después de que se complete la copia de seguridad.
* Los recursos de ámbito de clúster se incluyen en un backup, una copia de Snapshot o un clon si se hace referencia explícitamente a estos en la definición de la aplicación o si tienen referencias a cualquiera de los espacios de nombres de la aplicación.


====
[role="tabbed-block"]
====
.Crear un horario mediante un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre `trident-protect-schedule-cr.yaml`.
. En el archivo creado, configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre único y sensible para su entorno.
** *SPEC.DATAMOVER*: (_Optional_) Una cadena que indica qué herramienta de copia de seguridad usar para la operación de copia de seguridad. Valores posibles (distingue mayúsculas de minúsculas):
+
*** `Restic`
*** `Kopia` (predeterminado)


** *Spec.applicationRef*: El nombre de Kubernetes de la aplicación para realizar una copia de seguridad.
** *Spec.appVaultRef*: (_required_) El nombre del AppVault donde se debe almacenar el contenido de la copia de seguridad.
** *spec.backupRetention*: (_Obligatorio_) La cantidad de copias de seguridad a conservar. Cero indica que no se deben crear copias de seguridad (solo instantáneas).
** *spec.backupReclaimPolicy*: (_Opcional_) Determina qué sucede con una copia de seguridad si el CR de la copia de seguridad se elimina durante su período de retención.  Después del período de retención, las copias de seguridad siempre se eliminan. Valores posibles (distingue entre mayúsculas y minúsculas):
+
*** `Retain` (predeterminado)
*** `Delete`


** *spec.snapshotRetention*: (_Obligatorio_) La cantidad de instantáneas a conservar. El valor cero indica que no se deben crear instantáneas.
** *spec.snapshotReclaimPolicy*: (_Opcional_) Determina qué sucede con una instantánea si el CR de la instantánea se elimina durante su período de retención.  Después del período de retención, las instantáneas siempre se eliminan. Valores posibles (distingue entre mayúsculas y minúsculas):
+
*** `Retain`
*** `Delete`(por defecto)


** *spec.granularity*: La frecuencia con la que debe ejecutarse el horario. Los posibles valores, junto con los campos asociados necesarios:
+
*** `Hourly`(requiere que usted especifique `spec.minute` )
*** `Daily`(requiere que usted especifique `spec.minute` y `spec.hour` )
*** `Weekly`(requiere que usted especifique `spec.minute, spec.hour` , y `spec.dayOfWeek` )
*** `Monthly`(requiere que usted especifique `spec.minute, spec.hour` , y `spec.dayOfMonth` )
*** `Custom`


** *spec.dayOfMonth*: (_Opcional_) El día del mes (1 - 31) en que debe ejecutarse la programación.  Este campo es obligatorio si la granularidad está establecida en `Monthly` .  El valor debe proporcionarse como una cadena.
** *spec.dayOfWeek*: (_Opcional_) El día de la semana (0 - 7) en que debe ejecutarse la programación.  Los valores de 0 o 7 indican domingo.  Este campo es obligatorio si la granularidad está establecida en `Weekly` .  El valor debe proporcionarse como una cadena.
** *spec.hour*: (_Opcional_) La hora del día (0 - 23) en que debe ejecutarse el programa.  Este campo es obligatorio si la granularidad está establecida en `Daily` , `Weekly` , o `Monthly` .  El valor debe proporcionarse como una cadena.
** *spec.minute*: (_Opcional_) El minuto de la hora (0 - 59) en que debe ejecutarse el programa.  Este campo es obligatorio si la granularidad está establecida en `Hourly` , `Daily` , `Weekly` , o `Monthly` .  El valor debe proporcionarse como una cadena.
+
Ejemplo de YAML para programación de copias de seguridad y instantáneas:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  namespace: my-app-namespace
  name: my-cr-name
spec:
  dataMover: Kopia
  applicationRef: my-application
  appVaultRef: appvault-name
  backupRetention: "15"
  snapshotRetention: "15"
  granularity: Daily
  hour: "0"
  minute: "0"
----
+
Ejemplo de YAML para una programación de solo instantáneas:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  namespace: my-app-namespace
  name: my-snapshot-schedule
spec:
  applicationRef: my-application
  appVaultRef: appvault-name
  backupRetention: "0"
  snapshotRetention: "15"
  granularity: Daily
  hour: "2"
  minute: "0"
----


. Después de rellenar `trident-protect-schedule-cr.yaml` el archivo con los valores correctos, aplique el CR:
+
[source, console]
----
kubectl apply -f trident-protect-schedule-cr.yaml
----


--
.Cree una programación con la CLI
--
.Pasos
. Cree el programa de protección, reemplazando los valores entre paréntesis con información de su entorno. Por ejemplo:
+

NOTE: Puede usar `tridentctl-protect create schedule --help` para ver información de ayuda detallada de este comando.

+
[source, console]
----
tridentctl-protect create schedule <my_schedule_name> \
  --appvault <my_appvault_name> \
  --app <name_of_app_to_snapshot> \
  --backup-retention <how_many_backups_to_retain> \
  --backup-reclaim-policy <Retain|Delete (default Retain)> \
  --data-mover <Kopia_or_Restic> \
  --day-of-month <day_of_month_to_run_schedule> \
  --day-of-week <day_of_week_to_run_schedule> \
  --granularity <frequency_to_run> \
  --hour <hour_of_day_to_run> \
  --minute <minute_of_hour_to_run> \
  --recurrence-rule <recurrence> \
  --snapshot-retention <how_many_snapshots_to_retain> \
  --snapshot-reclaim-policy <Retain|Delete (default Delete)> \
  --full-backup-rule <string> \
  -n <application_namespace>
----
+
Puede establecer `--full-backup-rule` la marca en `always` para una copia de seguridad completa constante o personalizarla según sus necesidades. Por ejemplo, si elige una granularidad diaria, puede especificar los días de la semana en los que debe realizarse el backup completo. Por ejemplo, utilice `--full-backup-rule "Monday,Thursday"` para programar un backup completo los lunes y jueves.

+
Para programaciones de solo instantáneas, configure `--backup-retention 0` y especifique un valor mayor que 0 para `--snapshot-retention` .



--
====


=== Anotaciones de programación admitidas

La siguiente tabla describe las anotaciones que puede utilizar al crear una solicitud de cambio de programación:

[cols="2,1,3,1"]
|===
| Anotación | Tipo | Descripción | Valor predeterminado 


| proteger.trident.netapp.io/regla-de-copia-de-seguridad-completa | cadena | Especifica la regla para programar copias de seguridad completas. Puedes configurarlo para `always` para copias de seguridad completas constantes o personalícelo según sus necesidades. Por ejemplo, si elige una granularidad diaria, puede especificar los días de la semana en los que debe realizarse la copia de seguridad completa (por ejemplo, `"Monday,Thursday"` ). | No configurado (todas las copias de seguridad son incrementales) 


| protect.trident.netapp.io/snapshot-complete-timeout | cadena | Tiempo máximo permitido para que se complete la operación de instantánea general. | "60 m" 


| protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout | cadena | Tiempo máximo permitido para que las instantáneas de volumen alcancen el estado listo para usar. | "30 m" 


| protect.trident.netapp.io/volume-snapshots-created-timeout | cadena | Tiempo máximo permitido para la creación de instantáneas de volumen. | "5 m" 


| protect.trident.netapp.io/pvc-bind-timeout-sec | cadena | Tiempo máximo (en segundos) que se debe esperar para que cualquier PersistentVolumeClaim (PVC) recién creado llegue al `Bound` fase antes de que fallen las operaciones. | "1200" (20 minutos) 
|===


== Eliminar una copia de Snapshot

Elimine las snapshots programadas o bajo demanda que ya no necesite.

.Pasos
. Elimine el CR de instantánea asociado a la instantánea:
+
[source, console]
----
kubectl delete snapshot <snapshot_name> -n my-app-namespace
----




== Eliminar una copia de seguridad

Elimine los backups programados o bajo demanda que ya no necesita.


NOTE: Asegúrese de que la política de recuperación esté configurada en  `Delete` Para eliminar todos los datos de respaldo del almacenamiento de objetos. La configuración predeterminada de la política es  `Retain` Para evitar la pérdida accidental de datos. Si la política no se modifica a  `Delete` Los datos de respaldo permanecerán en el almacenamiento de objetos y será necesario eliminarlos manualmente.

.Pasos
. Elimine el CR de backup asociado con el backup:
+
[source, console]
----
kubectl delete backup <backup_name> -n my-app-namespace
----




== Compruebe el estado de una operación de backup

Puede usar la línea de comandos para comprobar el estado de una operación de backup que está en curso, se completa o tiene errores.

.Pasos
. Utilice el siguiente comando para recuperar el estado de la operación de copia de seguridad, sustituyendo los valores entre corchetes por información de su entorno:
+
[source, console]
----
kubectl get backup -n <namespace_name> <my_backup_cr_name> -o jsonpath='{.status}'
----




== Permita el backup y la restauración para las operaciones de azure-NetApp-files (ANF)

Si ha instalado Trident Protect, puede habilitar la funcionalidad de copia de seguridad y restauración que ahorra espacio para los backends de almacenamiento que usan la clase de almacenamiento azure-netapp-files y se crearon antes de Trident 24.06. Esta funcionalidad funciona con volúmenes NFSv4 y no consume espacio adicional del grupo de capacidad.

.Antes de empezar
Asegúrese de lo siguiente:

* Ha instalado Trident Protect.
* Ha definido una aplicación en Trident Protect. Esta aplicación tendrá una funcionalidad de protección limitada hasta que complete este procedimiento.
*  `azure-netapp-files`Seleccionó como clase de almacenamiento predeterminada para el back-end de almacenamiento.


.Expanda para obtener pasos de configuración
[%collapsible]
====
. Haga lo siguiente en Trident si el volumen ANF se creó antes de actualizar a Trident 24,10:
+
.. Habilite el directorio de instantáneas para cada VP basado en azure-NetApp-files y asociado con la aplicación:
+
[source, console]
----
tridentctl update volume <pv name> --snapshot-dir=true -n trident
----
.. Confirme que el directorio de snapshots se haya habilitado para cada VP asociado:
+
[source, console]
----
tridentctl get volume <pv name> -n trident -o yaml | grep snapshotDir
----
+
Respuesta:

+
[listing]
----
snapshotDirectory: "true"
----
+
Cuando el directorio de instantáneas no está habilitado, Trident Protect elige la funcionalidad de copia de seguridad regular, que consume temporalmente espacio en el grupo de capacidad durante el proceso de copia de seguridad. En este caso, asegúrese de que haya suficiente espacio disponible en el grupo de capacidad para crear un volumen temporal del tamaño del volumen del que se está realizando la copia de seguridad.





.Resultado
La aplicación está lista para realizar copias de seguridad y restaurar mediante Trident Protect. Cada PVC también está disponible para ser utilizado por otras aplicaciones para copias de seguridad y restauraciones.

====