---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'Trident Protect permite a los administradores generar paquetes que incluyen información útil para el soporte de NetApp , incluidos registros, métricas e información de topología sobre los clústeres y las aplicaciones bajo administración. Si está conectado a Internet, puede cargar paquetes de soporte al sitio de soporte de NetApp (NSS) utilizando un archivo de recursos personalizados (CR).' 
---
= Generar un paquete de soporte de Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect permite a los administradores generar paquetes que incluyen información útil para el soporte de NetApp , incluidos registros, métricas e información de topología sobre los clústeres y las aplicaciones bajo administración. Si está conectado a Internet, puede cargar paquetes de soporte en el sitio de soporte de NetApp (NSS) mediante un archivo de recursos personalizados (CR).

[role="tabbed-block"]
====
.Cree un paquete de soporte mediante un CR
--
.Pasos
. Cree el archivo de recursos personalizados (CR) y asígnele un nombre (por ejemplo, `trident-protect-support-bundle.yaml`).
. Configure los siguientes atributos:
+
** *metadata.name*: (_required_) El nombre de este recurso personalizado; elija un nombre único y sensible para su entorno.
** *Spec.triggerType*: (_required_) Determina si el paquete de soporte se genera inmediatamente o se programa. La generación de paquetes programada se tiene lugar a LAS 12am UTC. Los posibles valores son los siguientes:
+
*** Programado
*** Manual


** *SPEC.uploadEnabled*: (_Opcional_) Controla si el paquete de soporte debe cargarse en el sitio de soporte de NetApp después de que se genere. Si no se especifica, el valor por defecto es `false`. Los posibles valores son los siguientes:
+
*** verdadero
*** false (predeterminado)


** *Spec.dataWindowStart*: (_Optional_) Una cadena de fecha en formato RFC 3339 que especifica la fecha y la hora en que debe comenzar la ventana de datos incluidos en el paquete de soporte. Si no se especifica, el valor predeterminado es hace 24 horas. La fecha de ventana más antigua que puede especificar es hace 7 días.
+
Ejemplo YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. Después de rellenar el `trident-protect-support-bundle.yaml` archivo con los valores correctos, aplicar la CR:
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml -n trident-protect
----


--
.Cree un bundle de soporte mediante la CLI
--
.Pasos
. Cree el paquete de soporte, reemplazando valores entre paréntesis con la información del entorno.  `trigger-type`Determina si el grupo se crea inmediatamente o si la hora de creación está determinada por la programación, y puede ser `Manual` o. `Scheduled` El valor predeterminado es `Manual`.
+
Por ejemplo:

+
[source, console]
----
tridentctl-protect create autosupportbundle <my-bundle-name> --trigger-type <trigger-type> -n trident-protect
----


--
====


== Supervisar y recuperar el paquete de soporte

Después de crear un paquete de soporte utilizando cualquiera de los métodos, puede supervisar el progreso de su generación y recuperarlo en su sistema local.

.Pasos
. Espera a que `status.generationState` Para alcanzar `Completed` estado.  Puede monitorear el progreso de la generación con el siguiente comando:
+
[source, console]
----
kubectl get autosupportbundle trident-protect-support-bundle -n trident-protect
----
. Recupere el paquete de soporte para su sistema local.  Obtenga el comando de copia del paquete AutoSupport completado:
+
[source, console]
----
kubectl describe autosupportbundle trident-protect-support-bundle -n trident-protect
----
+
Encuentra el `kubectl cp` comando desde la salida y ejecútelo, reemplazando el argumento de destino con su directorio local preferido.


