---
sidebar: sidebar 
permalink: trident-reference/rest-api.html 
keywords: rest api, get, post, json, object, backends 
summary: Puede usar el extremo REST directamente si prefiere interactuar con la API REST de Trident. 
---
= API de REST de Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si bien link:tridentctl.html["comandos y opciones de trimentctl"] es la forma más sencilla de interactuar con la API DE REST DE Trident, puede usar el extremo de REST directamente, si lo prefiere.



== Cuándo utilizar la API DE REST

La API de REST es útil para instalaciones avanzadas que usan Trident como binario independiente en puestas en marcha que no son de Kubernetes.

Para una mayor seguridad, Trident `REST API` está restringido a localhost de forma predeterminada cuando se ejecuta dentro de un pod. Para cambiar este comportamiento, debe establecer el argumento de Trident `-address` en su configuración de pod.



== Uso de la API DE REST

Para ver ejemplos de cómo se llaman a estas API, pase (`-d`el indicador DEBUG ). Para obtener más información, consulte link:../trident-managing-k8s/tridentctl.html["Gestione Trident con tridentctl"].

La API funciona de la siguiente manera:



=== OBTENGA

`GET <trident-address>/trident/v1/<object-type>`:: Muestra todos los objetos de ese tipo.
`GET <trident-address>/trident/v1/<object-type>/<object-name>`:: Obtiene los detalles del objeto con nombre.




=== PUBLICAR

`POST <trident-address>/trident/v1/<object-type>`:: Crea un objeto del tipo especificado.
+
--
* Requiere la configuración de JSON para el objeto que se cree. Para conocer la especificación de cada tipo de objeto, consulte link:../trident-managing-k8s/tridentctl.html["Gestione Trident con tridentctl"].
* Si el objeto ya existe, el comportamiento varía: Los back-ends actualizan el objeto existente, mientras que todos los demás tipos de objeto fallarán la operación.


--




=== ELIMINAR

`DELETE <trident-address>/trident/v1/<object-type>/<object-name>`:: Suprime el recurso con nombre.
+
--

NOTE: Seguirán existiendo volúmenes asociados con back-ends o clases de almacenamiento, que deben eliminarse por separado. Para obtener más información, consulte link:../trident-managing-k8s/tridentctl.html["Gestione Trident con tridentctl"].

--

